### ISSUE TITLE
Tip: Update the site theme and give it an easier interface

### ISSUE THREAD

**Issue by eqMFqfFd** [poggit/poggit#101]

**Comment by SOF3** [comment]
Poggit's theme was initially made to be generally similar to that of GitHub. Personally, I hate excessive colors.

**Comment by SOF3** [comment]
Because Poggit is not merely a plugin download/upload site. It should be made to be easy to download plugins, but for submitting plugins, the flow is a bit different. I admit that the UI is not very user-friendly right now, but an interface like the forums one is not suitable here.

**Comment by SOF3** [comment]
Closing as this duplicates #21
