### ISSUE TITLE
Add better explaination how to create virons/libraries

### ISSUE THREAD

**Issue by inxomnyaa** [poggit/poggit#106]
And when to use them. Example you often told me to make a viron/library: BossBarAPI.

**Comment by inxomnyaa** [comment]
Maybe also add a Wiki

**Comment by SOF3** [comment]
The initial proposal: #14 
The official ~~specification~~ half-specification-45%-documentation-5%-tutorial: https://github.com/poggit/support/blob/master/virion.md (quite incomplete)

I shall update virion.md in the future.

**Comment by inxomnyaa** [comment]
As of #14 i'll close as duplicate

**Comment by SOF3** [comment]
N.B. #14 is only the initial proposal and is inconsistent with the current implementation from several aspects.

**Comment by inxomnyaa** [comment]
Well then.. May i open a new issue with CSS concepts for poggit to make it way more user friendly? ( #21 )

**Comment by SOF3** [comment]
https://github.com/poggit/support/blob/master/virion.md
