### ISSUE TITLE
Combination of ProjectBuildPage and BuildBuildPage

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#113]
ProjectBuildPage and BuildBuildPage have very little information to display. On desktops, it is best if they are combined such that clicking on a build in the build list opens its details.

URL BC will be preserved through location.pushState().

I am uncertain how to implement this on mobile.
@Awzaw Any UI tips for that?

**Comment by Awzaw** [comment]
Maybe JQuery tabs?

**Comment by SOF3** [comment]
I'm thinking if popups would be a better idea on mobile.
