### ISSUE TITLE
Internal Server Error attempting to update a plugin

### ISSUE THREAD

**Issue by Sandertv** [poggit/poggit#121]
After a couple months I decided it was time to push an update to poggit again, but when attempting to do so, I got a `500 Internal Server Error`.
I tried updating by going to CI -> BlockSniper -> Build History -> Action -> Update. As soon as clicking the `Update` button, the error showed up.

![image](https://user-images.githubusercontent.com/16114089/31427895-2ebfd608-ae69-11e7-94b2-e6898ce9d296.png)

**Comment by Awzaw** [comment]
Was the project renamed?

**Comment by Sandertv** [comment]
It wasn't renamed, but it was moved from my GitHub account to an organisation some time ago.

**Comment by Awzaw** [comment]
Can you try this?  Get the project ID from the project page and add it as "projectId: xx" in .poggit.yml

**Comment by Sandertv** [comment]
The following:
https://github.com/BlockHorizons/BlockSniper/commit/966ba5235fa3999c68c7504cb1275c54fd41f269 
continued to give the error.

**Comment by Awzaw** [comment]
Poggit is looking for your .yml file in the root folder, not in the .poggit subfolder.... try moving it up a level.

**Comment by Sandertv** [comment]
That works, thanks!

Weird it does build correctly when it's in that folder though.

**Comment by Awzaw** [comment]
It should work there too, yes, so I'll leave this open

**Comment by SOF3** [comment]
.poggit/.poggit.yml was a legacy location of the file, when Poggit was just started and I expected there to be more than one file related to Poggit. Ends up that all files you need with Poggit can just be referenced directly (e.g. `icon`).

**Comment by SOF3** [comment]
.poggit/.poggit.yml should be deprecated. I shall send out deprecation notice now.

**Comment by SOF3** [comment]
.poggit/.poggit.yml has been officially deprecated.
