### ISSUE TITLE
More shields

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#130]
We can add shields like these:

![](https://img.shields.io/badge/poggit%20release-featured-brightgreen.svg)
![](https://img.shields.io/badge/poggit%20release-approved-green.svg)

![](https://img.shields.io/badge/release%20api-3.0.0--ALPHA9-brightgreen.svg)
![](https://img.shields.io/badge/release%20api-3.0.0--ALPHA7-yellowgreen.svg)
![](https://img.shields.io/badge/release%20api-2.1.0-red.svg)

![](https://img.shields.io/badge/downloads-1000-brightgreen.svg)
![](https://img.shields.io/badge/downloads-500-green.svg)
![](https://img.shields.io/badge/downloads-200-yellowgreen.svg)
![](https://img.shields.io/badge/downloads-25-yellow.svg)

All with links to the Poggit release page.

**Comment by HimbeersaftLP** [comment]
How about (release|version) and (release|commit) too?

**Comment by SOF3** [comment]
I'm not very sure about the "approved" badge, because it is meaningless once the first version is approved.

**Comment by SOF3** [comment]
Implemented in f404ddc:

![](https://poggit.pmmp.io/shield.dl/DevTools) https://poggit.pmmp.io/shield.dl/DevTools
![](https://poggit.pmmp.io/shield.dl.total/DevTools) https://poggit.pmmp.io/shield.dl.total/DevTools
![](https://poggit.pmmp.io/shield.dl.total/Colormatic) https://poggit.pmmp.io/shield.dl.total/Colormatic
![](https://poggit.pmmp.io/shield.approved/DevTools) https://poggit.pmmp.io/shield.approved/DevTools
![](https://poggit.pmmp.io/shield.approved/TicTacToe) https://poggit.pmmp.io/shield.approved/TicTacToe
![](https://poggit.pmmp.io/shield.spoon/DevTools) https://poggit.pmmp.io/shield.spoon/DevTools
![](https://poggit.pmmp.io/shield.spoon/LiveXYZ) https://poggit.pmmp.io/shield.spoon/LiveXYZ
![](https://poggit.pmmp.io/shield.spoon/Hormones) https://poggit.pmmp.io/shield.spoon/Hormones

The color constraints might also need tuning.

We still need convenient copy-paste boxes in ReleaseDetailsModule.

**Comment by HimbeersaftLP** [comment]
In my opinion the Poggit badges shadow is too opaque/dark when compared to other "shield-type" badges (e.g. Travis) which makes it look more "early 2000s pseudo 3D"
![Poggit and Travis badges compared](https://i.imgur.com/1PjNeYAl.jpg)

**Comment by SOF3** [comment]
You can add a style parameter, e.g. ![](https://poggit.pmmp.io/shield.spoon/DevTools?style=for-the-badge&left=https://poggit.pmmp.io/p/DevTools&right=https://github.com/pmmp/PocketMine-MP/tree/api/3.0.0-ALPHA9) https://poggit.pmmp.io/shield.spoon/DevTools?style=for-the-badge

**Comment by HimbeersaftLP** [comment]
Why does it default to plastic though?

**Comment by SOF3** [comment]
Because it's the first one in the shields.io list, and I thought it was the default :P
(yes, now I see the line above)

**Comment by SOF3** [comment]
@Awzaw If you have time, please add the supported badges to somewhere appropriate in ReleaseDetailsModule. (Probably only to the owner(s))

**Comment by Awzaw** [comment]
By "Add' do you mean provide a link to copy for each badge? Or markdown? Or both?

**Comment by SOF3** [comment]
Maybe both, like what we did with CI badges before?
