### ISSUE TITLE
No easy/obvious way to get from builds page to releases

### ISSUE THREAD

**Issue by robske110** [poggit/poggit#131]
For some instances the [R] is buried well below tens of builds and you have to scroll and spam the "Load more builds" buttons to get to it.
I'd suggest to have a big button "To the latest release" above the buildlist.

**Comment by Awzaw** [comment]
Sounds good, also the `R` only appears in repos for which you have admin access

**Comment by Awzaw** [comment]
I've made some changes to this: it'll now show you your latest release and prerelease (even if only submitted, for your own plugins). Still not perfect as the 'update' option still shows for builds you are not allowed to use because you already submitted a release, for example.
