### ISSUE TITLE
Updating an not approved plugin

### ISSUE THREAD

**Issue by Ad5001** [poggit/poggit#132]
I was uploading a plugin on poggit that I uploaded as a release. After that, I realized that I made a mistake, which I commited. But I could not "update" the not approved plugin on poggit. I had to delete the release.
But with a recent poggit update, it looks like the delete release button is gone.

**Comment by robske110** [comment]
You can restore to draft and then update the draft as far as i know.

**Comment by Ad5001** [comment]
Don't see any button for that either...

**Comment by robske110** [comment]
Well, that's (probably?) a bug then. I have restored the release to a draft for you. Now you can submit a new release with the same version name.
Was this button really not there for you?
<img width="1078" alt="data" src="https://user-images.githubusercontent.com/16020100/32237213-a9536500-be64-11e7-8f4d-3c7923d88615.png">

**Comment by Ad5001** [comment]
I don't even see the edit button. Maybe it changed location and I didn't found it? Btw, here's what I see on the draft:
https://screenshots.firefox.com/azHg4YbCbHLB9UCH/poggit.pmmp.io

**Comment by Ad5001** [comment]
Thanks anyway.

**Comment by Awzaw** [comment]
Fixed?

**Comment by Ad5001** [comment]
Yes, looks as so.
