### ISSUE TITLE
Remove plugin

### ISSUE THREAD

**Issue by lukeeey** [poggit/poggit#136]
How do i remove my plugin https://poggit.pmmp.io/p/JellyLegs?

**Comment by Awzaw** [comment]
I've set it back to draft, and you can disable the repo or request a compete delete

**Comment by lukeeey** [comment]
While it's in draft, would it be possible to submit a plugin under the same name on my new account?

**Comment by Thunder33345** [comment]
please try to use poggit/support next time for support related questions

**Comment by lukeeey** [comment]
Oh yeah lol

**Comment by SOF3** [comment]
Just transfer your repo to another GitHub account, or rename your GitHub account. Poggit uses the GitHub repo owner name as the plugin author name.
