### ISSUE TITLE
Submit/Update/Edit TODOs

### ISSUE THREAD

**Issue by Awzaw** [poggit/poggit#137]
- [x] Editing an associated plugin requires the user to re-enter the parent plugin manually before 'Save'.

- [x] Associated plugins cannot list the parent as a required dependency. This might be deliberate... but it should be clear that the parent is a required dependency, not just part of the list of associated plugins.

- [x] When editing a plugin which is > checked, the user is allowed to add an API row, but the drop-downs are disabled.

- [x] It is impossible to save the plugin if a github contributors account no longer exists. The name does display in red, and can be removed manually, but it is not always obvious why the plugin will not save.

- [x] As already agreed, `+` should be disallowed in version names

- [x] The licence popup should close on click-outside, and the 'close' tooltip' hidden on open.

- [ ] Replace tables for assocs, deps and reqs with flex divs. This is a minefield :-/

- [x]  Disallow setting a plugin as an associate of a plugin for which the user does not have push perms

- [x] Add waiting animation for pages that take time to load, fix strikethrough on submit error

**Comment by JaxkDev** [comment]
@SOF3 All thats left here is the + in version names, is this still wanted?

**Comment by SOF3** [comment]
probably. `+` in URL is just tricking people to incorrectly pass a space.
