### ISSUE TITLE
Reviews not displayed effectively

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#141]
Problem in ReleaseDetailsModule:
* There is a large gap between the main content (changelog) and the reviews.
* Could also add a button to skip to review
* Show review summary, e.g. mean score

Problem in ReleaseListModule:
* pluginPanel does not display reviews, although it's in the HTML data.

**Comment by SOF3** [comment]
Same for download count.

**Comment by JaxkDev** [comment]
Is any of this still relevant, Looks like most if not all has been changed from the desc.
