### ISSUE TITLE
Promoting /pi over /dev

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#146]
Non-developers should totally ignore /ci unless they are downloading development builds for a specific project after trying its releases, or unless the plugin is still in pre-release stage (e.g. WorldEditArt-Lite).

Possible tasks:
- navmenu
  - [x] "Release" moved in front of "CI", renamed to "Releases" as of 23b41b55e59ecb9f04e593dcabb845c29ec95667
  - [x] "CI" is renamed to "Dev" as of 39d209b3a626afa55b65650da5e42a54ce9f9638
- homepage
  - guest
    - [ ] A better homepage to show featured information e.g. plugin list, rather than a screen full of text.
  - member
    - [ ] "Recent Builds" should not be displayed.
- /ci
  - [x] display more warnings
  - [ ] more references to /ci
- /plugins
  - increase usability
- outside Poggit
  - [x] More Poggit shields pointing to the /p release rather than the /ci development build.

**Comment by JaxkDev** [comment]
Are these `homepage` tasks still wanted?

**Comment by SOF3** [comment]
I think it is fine rn. I don't see too many people trying to download CI builds directly. Probably because they'd rather download zip from github directly instead...
