### ISSUE TITLE
API + More dynamic UI

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#15]
Add more API for other people to create clients for poggit.

Use more AJAX to load data so that the UI is more responsive.

**Comment by Awzaw** [comment]
I'd leave more API until later... AJAX would be good for a multisearchbox in particular

**Comment by SOF3** [comment]
Ajax responses are basically API, except that they have different methods of authentication.

**Comment by SOF3** [comment]
This issue is a bit too vague... Let's close this.
