### ISSUE TITLE
Repo with CI disabled cannot be enabled again properly

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#157]
Because SelfBuildPage thinks it's enabled.

Repos like this have a row in `repos` table where `repos.build = 0`. SelfBuildPage should be made aware of it.

Steps to reproduce:
* Enable Poggit-CI for a repo
* Reload /ci
* Disable
* Reload /ci
* The repo is still shown as "On" in the admin panel.

**Comment by 95CivicSi** [comment]
@SOF3  Thanks for opening this.  I will be willing to test where possible.

**Comment by SOF3** [comment]
The old code is very spaghetti (and even worse, a mix of ES5 and ES6 code), so I'm not sure if things are done correctly. But as far as I have tested locally, it works.
