### ISSUE TITLE
Gamerules

### ISSUE THREAD

**Issue by Burgercat** [poggit/poggit#166]
Oh hi there!,

I just wanted to suggest to add the gamerule command. It frustrates me that when I want to customize my world settings, it just doesn't work. It just says Unknown Command bla bla bla.

Or i'm just a idiot not knowing how to use this...

**Comment by ghost** [comment]
👮

**Comment by SOF3** [comment]
Oh bye there!,

I just wanted to suggest to look at what the repo is about. It frustrates me that when I want to run away from PocketMine problems and stay a quiet corner in Poggit, it just doesn't work. It just says gamerules bla bla bla.

Or I'm just a idiot not knowing how to disable the issue tracker...
