### ISSUE TITLE
Older reviews by the same user should be disregarded

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#168]
See https://poggit.pmmp.io/p/Sheep/5.2.2 for example: SOFe reviewed twice, and both are displayed. While it is clear that the older review was for an older version, it also makes sense to have the newer review override the older one completely.

**Comment by Awzaw** [comment]
I think this only applies to staff who can leave multiple reviews, but I'll have to check

**Comment by JaxkDev** [comment]
Would like to see this changed, as anyone can review a new 'version' of the same plugin
Maybe when displaying a specific version display the reviews with it.
or just have the latest reviews.

**Comment by JaxkDev** [comment]
As discussed in #203 I wont entirely 'hide' the review but add a 'OUTDATED' tag in red next to the staff badge any thoughts on that?
