### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#17]
Create a deployment application for servers to manage (e.g. auto update) their plugins from Poggit plugin list.

**Comment by Thunder33345** [comment]
so that means another plugin on user's server that would check for existing plugin that is downloaded via poggit(somehow...) and updates it?

**Comment by SOF3** [comment]
Not plugin. A standalone program.

**Comment by Dog2puppy** [comment]
Maybe make a plugin alternative then?

**Comment by SOF3** [comment]
@Dog2puppy it is a bad idea to edit executing phar files.

**Comment by Dog2puppy** [comment]
@SOF3 Oh.

**Comment by SOF3** [comment]
Assigned to @KnownUnown in [Sheep](https://github.com/KnownUnown/Sheep).
