### ISSUE TITLE
error on importing sql

### ISSUE THREAD

**Issue by djdisodo** [poggit/poggit#171]
REATE TABLE release_perms(

releaseId INT UNSIGNED DEFAULT NULL ,
val TINYINT DEFAULT NULL ,
KEY release_meta_index( releaseId, TYPE ) , <---this line
FOREIGN KEY ( releaseId ) REFERENCES releases( releaseId ) ON DELETE CASCADE
);

MySQL message

#1072 - Key column 'type' doesn't exist in table

**Comment by SOF3** [comment]
Actually, the mysql.sql is a bit outdated, and I am not in the mood to update it. Several recent changes in the schema have not been documented in this file.
