### ISSUE TITLE
Question: Why not use an open-source framework?

### ISSUE THREAD

**Issue by jackbentley** [poggit/poggit#174]
Looking through the code, I can see that there's nearly no community-driven open-source code - and everything is self-coded.

What were the reasons for this? I would think that, for an open-source project, you would want to use an open-source framework like Symfony, Laravel, CakePHP, etc (to name a few).

If nothing else, it would make for less maintenance work - not having to maintain code that does the exact same thing that such frameworks already do - which are maintained by larger communities.

Edit: It also makes it much harder to get other developers on-board, as they will need to learn all the new code and how it goes together before they can even think about picking up something like a new feature request.

Edit 2: Also, consider security - I can see usage of raw `$_POST` variables without any input filtering.

**Comment by dktapps** [comment]
NIH syndrome. ¯\_(ツ)_/¯

**Comment by SOF3** [comment]
Can you give examples of the $_POST part?

**Comment by jackbentley** [comment]
@SOF3 Your latest commit - 51d59de7984a5fbc8eafb3598f3d71dde176ac4e

It's not a dig. You're obviously cable of understanding PHP - so why waste your time rewriting the basics, when theres large teams out there writing more code than you could ever possibly write on your own - that solves these problems for you - and give it you for free; update it regularly with new features and security fixes (ones you're probably not even aware of); have more tests than you can imagine; etc etc.

I've worked on projects that write all their code, like this, before - heck, I've written them myself many years ago - it just ends in a maintenance nightmare. You end up maintaining things like database abstraction and routing instead of actually writing the application it's self.

Not to mention.. you (or maybe you and a few others) are now the only people who can work on this project. No one can help you out, or submit PRs, without investing a large amount of their time learning the basics of your code - before actually writing the feature. And let's be honest.. no one wants to, or has the time to, do that.

I'd have happily contributed a bit here and there - maybe update some UI, or add some new API endpoints, write dev docs, etc. But I can't, because I really don't have the time to learn yet another proprietary framework. And this is exactly the same thing most full-time developers looking into this project will likely think.

If you were to write your project using an open source framework, then, I would either already know how to do basic things like adding a new page; or I could very easily find out, by reading the really well written docs that frameworks, like the ones I mentioned, have available. I could, within minutes, help you out and submit PRs. I don't have hours to read all your code.

I'd highly recommend using [Symfony](https://symfony.com/) or [Laravel](https://laravel.com/). But others are available.. [Slim](https://www.slimframework.com/); [Cake PHP](https://cakephp.org/); [Yii](https://www.yiiframework.com/); [Zend](https://framework.zend.com/); [Code Igniter](https://www.codeigniter.com/) to name just a few. They literally all do the same basic things, and allow you to **write the actual project**.

_Side note: just noticed there are no automated tests (not that I can find, anyway). Check out [PHPUnit](https://phpunit.de/); [PHPSpec](http://www.phpspec.net/); [Behat](http://behat.org/en/latest/); [Codeception](https://codeception.com/); [Kahlan](https://github.com/kahlan/kahlan); [PHP Parallel Lint](https://github.com/JakubOnderka/PHP-Parallel-Lint); not forgetting [PHPCS](https://github.com/squizlabs/PHP_CodeSniffer). Also, if you add such things, consider adding CI - check out [Travis CI](https://travis-ci.org/); [Circle CI](https://circleci.com/); many more available. All these things try to make sure nothing breaks, that you don't get more bug reports, that code is maintainable and able to be collaboratively written._

**Comment by SOF3** [comment]
I guess it is too late to think about this now without rewriting the whole project. When I started writing Poggit, I was indeed intending not to use those frameworks because I wanted to practise my programming and know more about the actual stuff like website security, program management, etc. I'm closing this issue since this cannot really be fixed.

**Comment by Awzaw** [comment]
All valid points @jackbentley, but in a way it's similar to the reason that PocketMine is written in PHP. With hindsight it seems obvious that Poggit should use a framework, but in both cases that's just how they happened, as SOFe explained above, and a rewrite at this point would be no simple matter. 

In Poggit's case you also need to bear in mind that although it is open-source, it wasn't written with any intention for users to actually install it themselves.

You never know though, maybe one day SOFe will want to learn a framework, and he'll choose a Poggit rewrite for practise...

**Comment by jackbentley** [comment]
It isn't really too late; it wouldn't necessarily require an entire rewrite - you don't have to implement a full-stack framework. The Symfony framework is broken down into [reusable modules](https://symfony.com/components). You could start implementing such modules one by one when you see fit, while adding new features.

There's also loads of other [cool packages available out there](https://packagist.org/explore/popular).

I feel like community is one of the big points about the project, and was one of the reasons why it was started. The statement regarding public self-installs and community written in the readme is very much on-point.

It's quite possible that, as this project grows and becomes more poplar, that it's no longer something you can maintain by yourselves alone - or, you might decide that you want to move onto new projects. In any which case, if you want to keep this project alive, you need to make sure the community has the tools and ability to maintain and iterate upon it.

Overall, I do highly recommend learning more about frameworks (and the tools around them) and how they can accelerate your development. It's something that'll help progress your developer career. Having people who know about, or are willing to learn about, these things are essential for any software team out there.

Wether you decide to experiment with them in this project, or a new one, is entirely up to you 😃
