### ISSUE TITLE
AutoUpdater

### ISSUE THREAD

**Issue by Melonenbubi** [poggit/poggit#177]
This Plugin should do what many Pocketmine-Server-Owner would love (because this Plugin will help them a lot)

This Plugin should include a command to update the server:
• New Pocketmine will be installed
• Plugins will be API bumped (Just changes the API in the plugin.yml (I'm not a real programmer - I hope I didn't say a false file name)
• The Plugin changes the API of itself

To say it short: This Plugin updates everything.

**Comment by SOF3** [comment]
This is not a place for requesting plugins.
