### ISSUE TITLE
Poggit mobile app

### ISSUE THREAD

**Issue by Guardian56** [poggit/poggit#178]
It might helping developer to directly manage their plugin without web. And easy to search plugin.

**Comment by Guardian56** [comment]
Idea: Make Firebase databade for Poggit so developer can be easy to access it

**Comment by SOF3** [comment]
What do you mean by "without web"? Modern web technologies allow a website to function almost as much as a mobile app. IMO what we need is a better-designed web frontend, not a separate platform-specific mobile app.

**Comment by nathfreder** [comment]
@SOF3 Definitely, the only issue is that Poggit is built using "old" web technologies. It would be a major challenge to do this.

**Comment by nathfreder** [comment]
Nevermind, I take that back. It is possible to turn this application into a Progressive Web App, though it would require a lot of changes to the core. Namely a frontend re-write. 🙁

**Comment by SOF3** [comment]
Closing due to lack of constructive discussion.
