### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#18]
- [x] Rate limit users from creating Poggit-CI (e.g. less than 60 builds per user per week)
- [x] Limit project sizes &dash; don't let people create builds that are too large! Limitations: < 10 MB repo zip, < 2 MB phar artifact
- [x] Fix XSS problems

**Comment by Awzaw** [comment]
I've never seen a PM plugin >500 kB, so I'd say 1 MB until you get complaints

**Comment by archie426** [comment]
@Awzaw Sounds like a plan

**Comment by Awzaw** [comment]
Sofe usually has his own, and always with good reason ;-)

**Comment by archie426** [comment]
@Awzaw And that is not a bad thing! (Not saying you did say it was). It is also usually right!

**Comment by SOF3** [comment]
Sometimes plugins may want to attach heavy files such as images or even worlds.

But indeed, if they do so, they should download the files JIT from the Internet instead. Not in the distributions.

**Comment by SOF3** [comment]
Well for exceptional cases they have to apply manually. Is this better?

**Comment by Thunder33345** [comment]
Does this counts as XSS
https://poggit.pmmp.io/%3Cscript%3Ealert(1)%3Cs/cript%3E
![Image](http://i.imgur.com/63gy4pu.png)
chrome seems to notice it and neutralizes it, but i doubt other web browser will do the same
nor i am 1337 enough to be bothered to find a chrome XSS detector bypass

**Comment by SOF3** [comment]
XSS problems mostly shot in https://github.com/poggit/poggit/commit/95df7f85f7562be88f0dde7acbc120a9d6c65082
