### ISSUE TITLE
Can't see on small width devices

### ISSUE THREAD

**Issue by ghost** [poggit/poggit#181]
Here's screen shots
![img_6433](https://user-images.githubusercontent.com/15015722/48800039-01e6cb00-ed4c-11e8-8ed9-e7ecc6cb3c78.JPG)
![img_6432](https://user-images.githubusercontent.com/15015722/48800044-0612e880-ed4c-11e8-85e5-74ff9df38375.JPG)

**Comment by SOF3** [comment]
Don't link to Dropbox. Copy your images and paste on GitHub directly, or click the "Upload files" button.

**Comment by SOF3** [comment]
@Awzaw any idea?

**Comment by ghost** [comment]
> Don't link to Dropbox. Copy your images and paste on GitHub directly, or click the "Upload files" button.

Sorry. uploaded directly

**Comment by Awzaw** [comment]
Which version of Safari is this, on which iOS?

**Comment by ghost** [comment]
> Which version of Safari is this, on which iOS?

Safari Version: 8.0
iOS: 8.4.1

**Comment by JaxkDev** [comment]
I have no way of testing this unfortunately, if anyone comes across this issue it can be re-opened by looking at site analytics cant see anyone using old browsers like mentioned ones.
