### ISSUE TITLE
Missing star rating

### ISSUE THREAD

**Issue by GamakCZ** [poggit/poggit#185]
![image](https://user-images.githubusercontent.com/17053298/58763373-22dd7380-855a-11e9-822c-ebf81cb3a20e.png)

![image](https://user-images.githubusercontent.com/17053298/58763381-3983ca80-855a-11e9-9ea4-5347e820954f.png)

https://poggit.pmmp.io/p/SimpleHome/

**Comment by SOF3** [comment]
Yes, it is a known issue that it only displays reviews for the latest version.

**Comment by JaxkDev** [comment]
I might be wrong in saying this but it could be because the releases they commented on aren't actually public anymore, 1.0.2 is rejected, 1.0 is draft.
It does show 1.0.1 reviews (if any were made)
