### ISSUE TITLE
reply, edit,love comments, pin comments fetures

### ISSUE THREAD

**Issue by Napoleon-x** [poggit/poggit#190]
please add these fetures so poggit can give the best feedback from developers and plugin authours
reply, edit,love comments, pin comments

**Comment by SOF3** [comment]
Poggit is not a forum.

**Comment by ghost** [comment]
@SOF3 Considering Poggit let's people add comments it's reasonable to ask for the ability to edit and reply to them. I'm not sure about loving and pinning comments though.
