### ISSUE TITLE
PoggitCI does not load builds.

### ISSUE THREAD

**Issue by ghost** [poggit/poggit#192]
![Uploading Screenshot_2019-08-03-13-48-14.png…]()
![Screenshot_2019-08-03-13-48-08](https://user-images.githubusercontent.com/49820135/62409746-7a996900-b5f5-11e9-9594-e0d1004296d3.png)
I don't see any error, problem with disc space or my quota?

**Comment by JaxkDev** [comment]
I came across this while doing something else, was when i didn't modify anything important (in the commit) it just skipped my build.

Simply: It doesn't build when it doesn't need to.

**Comment by JaxkDev** [comment]
Changed via #208
