### ISSUE TITLE
UI Not working

### ISSUE THREAD

**Issue by BroCrows** [poggit/poggit#196]
When I open up any UI on my sever and click any button it closes UI and if it has a closing message it sends closing message
My Plugins
EconomyAPI v5.7.2, SignEdit v1.4.6, EnchantUI v0.5, PiggyCustomEnchants v1.4.6, MultiWorld v1.5.1, AllSigns v1.0.11, BetterVoting v1.5.0, SellAll v1.3.0, OreGen v1.1.4, Sheep v5.2.3, PurePerms v1.4.2-c2a, RedstoneCircuit v1.0.1, WorldGuard v1.0.0, OreEarn v1.8.1, EasyHomes v1.0.2, CustomShopUI v4.0.5, Bounty v1.1.2, MissingItems v1.0.0, PureEntitiesX v0.6.3, FactionsPro v1.3.20, MysteryCrate v9.1.1, WorldTP v1.2.1, BuilderTools v1.2.0-beta2, WorldBorder v1.0.0-3.0.0, MSpawns v2.2, VanillaCoordinates v1.0.0, AntiInstaBreak v0.1.2, AutoXP v1.1.0, Enchantments_Disabler v1.0.0, NameSpaceRemover v1.0.0, EasyKits v1.0.0v0.1.2, AutoXP v1.1.0, Enchantments_Disabler v1.0.0, NameSpaceRemover v1.0.0, EasyKits v1.1.0

**Comment by BroCrows** [comment]
Why was my issue closed?

**Comment by ghost** [comment]
your issue does not include anything about poggit and your issue must be reported on the PocketMine-MP project not this, also that's not an bug. there's a plugin causing it. try removing your plugins and add them back one by one to know which one causing it.

**Comment by BroCrows** [comment]
Ok thanks
