### ISSUE TITLE
star,favourite,show newest options need to be added and add a reply to comments,edit comments and react to comments need to be added

### ISSUE THREAD

**Issue by Napoleon-x** [poggit/poggit#197]
star, favourite, show newest options need to be added and add a reply to comments, edit comments and react to comments need to be added

Make Poggit More User-Friendly Pls and oh god my eyes are bleeding please add a dark theme
I'm not asking for it to be a forum but it would be nice if we had them features

**Comment by jasonw4331** [comment]
Poggit dark: https://userstyles.org/styles/174539/poggit-dark

Poggit already has star ratings and allows users to leave reviews on plugins. What you are describing is a forum but we already have one, so this will not be turned into one. If you want to talk about the plugin with other users, then you can do so on https://forums.pmmp.io/

**Comment by SOF3** [comment]
What do you mean by "show newest options"?
For other things, they already have duplicate issues.
