### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by MyDeacy** [poggit/poggit#210]
![スクリーンショット (703)](https://user-images.githubusercontent.com/20610410/74599978-c614ef80-50cd-11ea-8b0d-a73ab5057bcd.png)
![スクリーンショット (704)](https://user-images.githubusercontent.com/20610410/74599992-f2c90700-50cd-11ea-8fff-9453fe73fba7.png)

My acquaintance can log in successfully, but I cannot log in.
The account is "MyDeacy" which is writing this issue now.

```
Fatal error: Uncaught poggit\utils\lang\NativeError: Level 0: Undefined index: id in /poggit/src/poggit/errdoc/InternalErrorPage.php#50 in /poggit/entry.php:69 Stack trace: #0 /poggit/src/poggit/errdoc/InternalErrorPage.php(50): poggit\error_handler(8, 'Undefined index...', '/poggit/src/pog...', 50, Array) #1 /poggit/src/poggit/utils/lang/Lang.php(150): poggit\errdoc\InternalErrorPage->output() #2 /poggit/entry.php(57): poggit\utils\lang\Lang::handleError(Object(RuntimeException)) #3 /var/www/html/index.php(23): include('/poggit/entry.p...') #4 {main} thrown in /poggit/entry.php on line 69
```

**Comment by SOF3** [comment]
How did you even manage to get the stack trace? 500 ISEs are supposed to give the request ID not the stack trace.

**Comment by SOF3** [comment]
Oh never mind, PHP is acting up. Can you reliably reproduce this issue?

**Comment by MyDeacy** [comment]
The way to reproduce is to log in with my account.
・ I have registered a plugin called MoneyLevel with ID RuinPrayMC before.

**Comment by JaxkDev** [comment]
Your account I presume is fixed, but please keep this open as there is a different issue attached to this one.

**Comment by MyDeacy** [comment]
Confirmed that I can log in.
thx :)

>  but please keep this open as there is a different issue attached to this one.

okay. leave open.
