### ISSUE TITLE
Virus infection. Json

### ISSUE THREAD

**Issue by Hydroxfr** [poggit/poggit#218]
Vérifier vos les plugin télécharger sur poggit github certain malin introduisent des virus infection. Json décompresser vos fichier phar avant de les exécuter sur votre console et vérifier les tous !

**Comment by Thunder33345** [comment]
Please use english
And do you think a real virus will name itself virus.json?
This is like going into a store while holding a large sign saying "I am a thief"

**Comment by Hydroxfr** [comment]
No speak English sorry, je comprend votre point de vue seulement c'est une movaisse blague j'ai recommencer tout mon travail avec leur conerie.
________________________________

**Comment by Thunder33345** [comment]
there's no viruses in any plugins on poggit, if there's any please link it here
https://poggit.pmmp.io/p/AuctionHouse/1.0.9 does not have any virus, `infection.json` is an internal poggit process

-----
Google traduit: il n'y a pas de virus dans les plugins sur poggit, s'il y en a, veuillez le lier ici
https://poggit.pmmp.io/p/AuctionHouse/1.0.9 ne contient aucun virus, `infection.json` est un processus interne de poggit

**Comment by Hydroxfr** [comment]
Dans ce cas je vous remercie pour l'information mais le nom de ce fichier json est confus j'ai recommencer tout mon serveur pmmp je suis démotiver à causse de leur bêtise. Désoler pour le dérangement

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by SOF3** [comment]
Nobody understands the language you are speaking. If you can't write English, just don't write, because a bunch of nonsense and an empty issue are equally useless to me.

"Virus" is the noun to describe a "virion" when it is injected inside a cell. The word "virus" here is more related to virus as in coronavirus than virus as in computer virus.
