### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#22]
A plugin request section can be held on Poggit, offering features that cannot be satisfied using a normal forum.

It is actually quite simple. Mainly need to enhance on how plugins are claimed, or filled.

**Comment by Magicode1** [comment]
This would be great idea.

I assume plugin Dev's would have to have a good reputation (Made a few good plugins) to claim stuff?

**Comment by SOF3** [comment]
Nope, it just marks him as "claimed". Multiple developers can declare to claim the request. If other developers think he is a noob and can't achieve anything, they can ignore his claim.

**Comment by Magicode1** [comment]
I see

**Comment by SOF3** [comment]
Also includes a tool to fill requests conveniently, like pmt.mcpe.me/insta.

**Comment by SOF3** [comment]
This is quite impractical now. I'm closing this.

**Comment by JaxkDev** [comment]
Would love to see this, added once all higher prior stuff is done !
