### ISSUE TITLE
Missing download button in dev: sidebar

### ISSUE THREAD

**Issue by Aericio** [poggit/poggit#235]
![image](https://user-images.githubusercontent.com/16523741/85220942-50ef4a80-b34b-11ea-806e-4d92ded4a26c.png)

**Comment by SOF3** [comment]
This issue matters when the user requests to download a specific build number.

In addition, API for CI builds shall be added. It was intentionally added in previous years in order to boost usage of Release over CI. However such a distinction is no loner desired, and an API to download directly e.g. `/ci.dl/:user/:repo/:project/:class\::build` shall be added.

**Comment by JaxkDev** [comment]
I'm actually confused with this issue, correct me if I'm wrong but do you want a download button inside the build 'box' eg underneath the `Link \n No problems have been found. Well done!` ?
You can already download a specific build number so think I'm missing something here...

**Comment by Aericio** [comment]
@JaxkDev Yes, download button directly in the sidebar and not just in the table.

My issue was that PiggyCustomEnchants has over 500 builds on Poggit.

If I manually edit the search bar like so to find the 300th build without needing to press "Load more builds" repetitively, 
`https://poggit.pmmp.io/ci/DaPigGuy/PiggyCustomEnchants/PiggyCustomEnchants/dev:300`

I will be able to see this specific development build on the side bar, but the table's position is still at top, and there's no way to download from the side bar.

> Aericio — 06/20/2020
is there a way to get all development builds faster? there are ~500 commits, and it only shows 10 more each time... takes a while.
since github now shows the latest release on the sidebar in the new UI, we decided that we'll be adding changelog / built phars to releases too. 
Aericio — 06/20/2020
there are ~500 commits, and it only shows 10 more each time... takes a while.
oh well, we got them anyways
SOFe — 06/20/2020
Why would you want to get them all?
Aericio — 06/20/2020
or well, specific ones
not all
SOFe — 06/20/2020
Click on one of the builds
Then edit the URL directly
The number behind dev: is the build number
Hmm right, the download button isn't there
Open an issue about this

**Comment by Aericio** [comment]
Thanks @JaxkDev.
