### ISSUE TITLE
[PHPStan] Autoload errors not captured

### ISSUE THREAD

**Issue by ghost** [poggit/poggit#237]
PHPStan will not work.

PHPStan Error
An error occurred while running PHPStan

PHPStan failed with ID 'phpstan-6f88-360a0e39', contact support with the ID for help if this persists.

**Comment by JaxkDev** [comment]
I assume it’s a private repo but it’s Friends.php L14 CommandSender and Command types weren’t found (add it at top with rest of ‘use’ statements)

**Comment by ghost** [comment]
I think not importing the 2 classes causes php Stan to crash. Once I fixed this the rest of the errors showed like they’re supposed to.

**Comment by dktapps** [comment]
Might be a good idea to use static reflection to avoid this. It doesn't crash on code errors that would be fatal with runtime reflection.

**Comment by JaxkDev** [comment]
https://poggit.pmmp.io/ci/PoggitTestPlugins/PoggitTestPlugin/PoggitTestPlugin/dev:29
