### ISSUE TITLE
Allow external URLs for icons

### ISSUE THREAD

**Issue by Aericio** [poggit/poggit#238]
> .poggit.yml declares an icon at https://raw.githubusercontent.com/Aericio/piggydocs-rtd/master/source/_static/img/piggyfactions/icon.png, but there is no such file in your repo! The default icon will be used; your plugin will not be considered for featuring without a custom icon.

I was hoping to move image files off of plugin repositories, but poggit doesn't support URLs. Perhaps you can have a list of allowed domains, such as `raw.githubusercontent.com`, that poggit would allow.

**Comment by JaxkDev** [comment]
Poggit already stores them as a `raw.githubusercontent.com` URL, Can't see why not, would also mean bigger size'd gifs / images could be used via different repo.

@SOF3 ?

**Comment by SOF3** [comment]
If it remains a canonical GitHub file path, I think it's fine. As long as we can ensure user can't change icon after submitting.

**Comment by Aericio** [comment]
Any update on this, or should I just add back the image to the repo? Someone brought to my attention that not having an icon hurts our visibility, also causing FactionsPro to gain more downloads than us in the past few months 😅 

I would probably have to submit a new version for this if I wanted to add it though.

**Comment by JaxkDev** [comment]
I won’t be adding this any time soon, bunch of other things more important to ‘fix’ but I don’t even have time for that right now, unless sofe does something probably won’t be implemented this year lol

**Comment by Aericio** [comment]
Alright

**Comment by JaxkDev** [comment]
Will look into this next week as I have the week off.

To have a non-changeable icon I think we’d have to only allow raw github url’s with specific commit hash.
(We can provide a default url, if we find a valid icon)

**Comment by JaxkDev** [comment]
Adding it into the `.poggit.yml`
```yml
icon: filename/path/url
```

where URL has to be:
```
https://raw.githubusercontent.com/USERNAME/REPO/COMMIT_ID/FILE.png
```

![image](https://github.com/poggit/poggit/assets/25908768/3a3bba3f-8ace-436e-90fe-64e5202ea0cc)

**Comment by Aericio** [comment]
Thank you for your work!
