### ISSUE TITLE
Bad plugins

### ISSUE THREAD

**Issue by MahdiDawat** [poggit/poggit#253]
Hello, if you can create a plugin for the registry, login
thanks a lot
SimpleAuth plugin does not work, we encounter the following error
Update API 3.0.0 3.17.0 Could not load plugin 'SimpleAuth': Incompatible API version (plugin requires one of: 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4)
Thank you. This plugin is very much needed

**Comment by MahdiDawat** [comment]
@Awzaw

**Comment by MahdiDawat** [comment]
Version 2.1.3 disappeared? @Awzaw @shoghicp @SOF3

**Comment by SOF3** [comment]
SimpleAuth is no longer updated. Please read the "Supported versions" section.

Also, we do not provide support for plugins here. Please visit the plugin repo using the ![octocat](https://poggit.pmmp.io/res/ghMark.png) button next to the plugin name.

**Comment by MahdiDawat** [comment]
Please update There are no plugins for server passwords and security

**Comment by MahdiDawat** [comment]
@SOF3 Update SimpleAuth Please

**Comment by SOF3** [comment]
> We do not provide support for plugins here. Please visit the plugin repo using the ![octocat](https://poggit.pmmp.io/res/ghMark.png) button next to the plugin name.
