### ISSUE TITLE
Unable to upload certain files

### ISSUE THREAD

**Issue by callumrawlinson** [poggit/poggit#259]
Hello, When i go to https://poggit.pmmp.io/ci/ and try to add my repo https://github.com/callumrawlinson/StaffUI it doesn't work!
it stays loading for 30-35 minutes before just not working.
![Screenshot 2021-01-21 at 09 24 24](https://user-images.githubusercontent.com/72660075/105330838-a84be680-5bca-11eb-82e7-045aee1a0593.png)

**Comment by SOF3** [comment]
Your repository is too large, and Poggit rejected downloading it.

Leaving this open as this is a UX issue.

**Comment by callumrawlinson** [comment]
What should i do?

**Comment by SOF3** [comment]
Delete your images. Poggit is not going to waste bandwidth downloading your 13MB-large images.

**Comment by SOF3** [comment]
At least use a more compact format than GIF.

**Comment by callumrawlinson** [comment]
ok sorry
