### ISSUE TITLE
Phpstan error

### ISSUE THREAD

**Issue by xXNiceYT** [poggit/poggit#260]
![9BBDE1CF-CB1A-420B-ABCB-8EBAB4FA998A](https://user-images.githubusercontent.com/23722462/105638189-5b247a80-5e3f-11eb-98fe-add873b39537.jpeg)

after I push a commit and I check Poggit I kept on getting this error.
Not sure if this is my fault or poggit.

https://poggit.pmmp.io/ci/CLADevs/VanillaX/VanillaX

**Comment by JaxkDev** [comment]
This still happening?
