### ISSUE TITLE
Invcrashfix

### ISSUE THREAD

**Issue by TheHumanCalculator** [poggit/poggit#262]
Could you add invcrashfix to poggit plz. I want to use the auction house plugins but both of them don't work unless you use invcrashfix. I can't download invcrashfix to aternos pocketmine server because it isn't on your website!

**Comment by mmm545** [comment]
ask the creator of the plugin to submit it to poggit

**Comment by ethaniccc** [comment]
ez solution, stop using Aternos

**Comment by SOF3** [comment]
Poggit does not create plugins. We just host submissions.
