### ISSUE TITLE
Plugins are not set to page 1 after approval

### ISSUE THREAD

**Issue by Wertzui123** [poggit/poggit#269]
When you submit a plugin, for whatever reason, it is placed on page 1 and over time it moves to pages 2, 3, and so on (I think because it has no downloads & is "older" than other plugins).
The problem is, it looks like plugins stay on this page after they are approved.
This is a **huge** disadvantage for plugins that take more time to review or when reviewers just have no time for a few days.

**Comment by SOF3** [comment]
We could change creation date to state change date in the query.

**Comment by JaxkDev** [comment]
Bit confused with this one, looks like it was designed to be by state date unless you recently changed it @SOF3 ?
https://github.com/poggit/poggit/blob/7af4ce0a25a4d5811b2c0904ac6809aa49b1e827/js/release.list.js#L19

**Comment by SOF3** [comment]
It should be by state date. I changed it a few times but eventually it should have been state date, and I haven't touched that part for many months

**Comment by JaxkDev** [comment]
tbh I personally think this should be a client sided sort, just send ‘all’ releases to client and leave them to decide how to sort them (based on UI options, eg API 3.0.0 compatible & order by downloads)

**Comment by Wertzui123** [comment]
Finally
