### ISSUE TITLE
submit.form.ajax crashes when plugin.yml lists nonexistent dependency

### ISSUE THREAD

**Issue by Bubbelwubbel** [poggit/poggit#271]
Hello,
I wanted to put a plugin public the last few days, but this does not work. I am logged in to Poggit with Github and have JavaScript on the page as well. In addition, I am using it correctly and that is why my question is why this is not possible?
FlxiBoy

Screen:
![image](https://user-images.githubusercontent.com/65186341/126785489-9ab76378-3c54-4c0a-9072-9e288e3af6c2.png)

**Comment by MrNinja008** [comment]
I can confirm this bug

**Comment by JaxkDev** [comment]
#207

remove FormAPI plugin dependency in plugin.yml

**Comment by MrNinja008** [comment]
Oh

**Comment by Bubbelwubbel** [comment]
only FormAPI?

**Comment by MrNinja008** [comment]
I am stoopid

**Comment by MrNinja008** [comment]
Yes remove FormAPI because it is not in POGGIT

**Comment by Bubbelwubbel** [comment]
I'll try right now, but thanks in advance! :)

**Comment by JaxkDev** [comment]
Any plugin that’s listed as a dependency on plugin.yml that’s not on poggit will cause a 500 template to be shown.

**Comment by Bubbelwubbel** [comment]
Okay thank you very much!
