### ISSUE TITLE
Add an "abandon" button

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#279]
Allows plugin developers to mark plugins as abandoned and provide recommended alternatives, similar to the "abandon" button in packagist.

**Comment by JaxkDev** [comment]
Should these plugins still be listed in plugins page?
(If so do we have an icon we could use)

I’m assuming a banner (like the one in EconomyAPI) would be used to provide notice & alternatives?

**Comment by SOF3** [comment]
I think just make it the same as marking plugin as outdated.
