### ISSUE TITLE
Namespace register repository

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#28]
Developers can "claim" namespaces they use. In the future this can be used for a wide range of purposes, such as:

* Preventing namespace collision
* Encourage proper naming of namespaces
* Allow third-party tools to query the information of a namespace

TODOs:
- [x] Tracking
- [ ] Listing
  - [x] Basic list: https://poggit.pmmp.io/fqn.txt
  - [ ] Better user interface

**Comment by Intyre** [comment]
What about ```namespace <author>\<pluginname>;```?

**Comment by SOF3** [comment]
@Intyre What if the name of the author is the name of the plugin?

**Comment by robske110** [comment]
Bad practise :P

**Comment by SOF3** [comment]
Why would naming your organization the name of the the plugin your organization be a bad practice?
