### ISSUE TITLE
Error AccessFilter.RepoNotFound when trying to download plugin from private Poggit CI builds on browser

### ISSUE THREAD

**Issue by KygekDev** [poggit/poggit#290]
I'm getting this error when trying to download a plugin from my private Poggit CI builds on browser:

```json
{"error":"AccessFilter.RepoNotFound","message":"Access to repo #422544877 (KygekDev/PrivatePluginTest) required. The repo is deleted or private to the provided access token. Access tokens can be provided using the Authorization header.","repo":{"id":422544877,"name":"PrivatePluginTest","owner":"KygekDev","requiredPerms":["pull"]}}
```

This is the page where I tried to download the plugin:

![image](https://user-images.githubusercontent.com/68368066/140497050-0e8b87c1-eeff-430f-bc6a-a28d4ed32415.png)

However, I am logged in to both GitHub and Poggit CI with my **KygekDev** account and I think that I have granted all necessary permissions:

![image](https://user-images.githubusercontent.com/68368066/140497393-2995c69e-5b64-4ebd-a284-da34791384bf.png)

I have tried re-logging and it didn't solve the issue.

What causes the issue and what can I do to solve the issue? Thanks.

---
### More information:
GitHub Repository: https://github.com/KygekDev/PrivatePluginTest
Poggit CI: https://poggit.pmmp.io/ci/KygekDev/PrivatePluginTest/PrivatePluginTest
Browser: Brave version 1.31.88 (Chromium version 95.0.4638.69) - 64-bit

**Comment by SOF3** [comment]
Have you reproduced this with a "normal" browser? I don't know if brave has any special cookie policy that breaks this.

**Comment by KygekDev** [comment]
> Have you reproduced this with a "normal" browser? I don't know if brave has any special cookie policy that breaks this.

I have also tried using Firefox with protection disabled, but the issue still persists.

**Comment by JaxkDev** [comment]
Reproduced, 

Investigation revealed its checking session_name() but this will ALWAYS be null because its set once the session is opened. (after that check)

**Comment by KygekDev** [comment]
For some reason, now I can't access my Poggit CI builds: https://poggit.pmmp.io/ci/KygekDev/PrivatePluginTest/PrivatePluginTest

![image](https://user-images.githubusercontent.com/68368066/141412143-875af39f-0a16-4699-a7b0-3c1d072edc56.png)

**Comment by KygekDev** [comment]
Still getting the same error even after the commit https://github.com/poggit/poggit/commit/5f28220038d037bd850d75c01c39d15b6301fd0e:

> I'm getting this error when trying to download a plugin from my private Poggit CI builds on browser:
> 
> ```json
> {"error":"AccessFilter.RepoNotFound","message":"Access to repo #422544877 (KygekDev/PrivatePluginTest) required. The repo is deleted or private to the provided access token. Access tokens can be provided using the Authorization header.","repo":{"id":422544877,"name":"PrivatePluginTest","owner":"KygekDev","requiredPerms":["pull"]}}
> ```
> 
> This is the page where I tried to download the plugin:
> 
> ![image](https://user-images.githubusercontent.com/68368066/140497050-0e8b87c1-eeff-430f-bc6a-a28d4ed32415.png)
> 
> However, I am logged in to both GitHub and Poggit CI with my **KygekDev** account and I think that I have granted all necessary permissions:
> 
> ![image](https://user-images.githubusercontent.com/68368066/140497393-2995c69e-5b64-4ebd-a284-da34791384bf.png)
> 
> I have tried re-logging and it didn't solve the issue.

What else could be causing this issue?

**Comment by JaxkDev** [comment]
Just because I’ve committed the fix doesn’t mean it’s live.
