### ISSUE TITLE
Build with same id for github actions

### ISSUE THREAD

**Issue by ShockedPlot7560** [poggit/poggit#291]
When we set up an action on our repository to for example automatically modify the style of the plugin with php cs fix, the plugin will bug. Indeed, if we activate the automatic commit, and that it is github-actions which commit, a same id for the build will be given and thus make bug the update via poggit. 
Let me explain: if two builds have the same id and we want to publish a new release, this will emit a 404 page and we will be blocked.
![image](https://user-images.githubusercontent.com/66992287/140937201-11c5d63f-d2ba-458f-8ec4-7e2536803092.png)
![image](https://user-images.githubusercontent.com/66992287/140937307-4de993c2-1068-4cc5-b9ab-33271263ee77.png)

**Comment by ShockedPlot7560** [comment]
And also, I have the impression that php stan is not performed on auttomatiq commits

**Comment by dktapps** [comment]
@SOF3 I told you you should have fixed this years ago :(

**Comment by SOF3** [comment]
Yes, but this is not easy to fix with the poor SQL usage

**Comment by JaxkDev** [comment]
Linked: #26
