### ISSUE TITLE
Something extremely broken is happening to BlockSniper lint

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit#292]
https://poggit.pmmp.io/ci/BlockHorizons/BlockSniper/~/pr:145

```
Violation of PSR-0
On line 206 at src/BlockHorizons/BlockSniper/brush/BrushProperties.php:

class TreePropeeProperties{
```
```
Violation of PSR-0
On line 127 at src/BlockHorizons/BlockSniper/data/ConfigData.php:

class BrushIteushItem{
```
```
Violation of PSR-0
On line 9 at src/marshal/src/Sandertv/Marshal/DataProcessor.php:

class DataProctaProcessor{
```
and many more besides.

**Comment by JaxkDev** [comment]
From memory this is fixed when updated to PHP8

**Comment by dktapps** [comment]
@SOF3 fix it pls

**Comment by JaxkDev** [comment]
Stand corrected, just got some things running locally this still occurs on PHP8.

**Comment by SOF3** [comment]
Related? https://poggit.pmmp.io/ci/PoggitTestPlugins/PoggitTestPlugin/PoggitTestPlugin/dev:21

**Comment by JaxkDev** [comment]
This looks like a visual error, `{"class":"\\Main","file":"src\/JaxkDev\/TestPlugin\/Main.php","line":6,"code":"class Main extends PluginBase{","hlSects":[[6,8]],"name":null}` produces
<img width="364" alt="Screenshot 2021-11-30 at 15 40 51" src="https://user-images.githubusercontent.com/25908768/144078824-7f3dd504-36fd-480d-baed-d4fa9cfb8963.png">
s

**Comment by JaxkDev** [comment]
Fixed for all **new** builds
