### ISSUE TITLE
Lint is still running on PHP 7.4 (or earlier?!)

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit#293]
```
Syntax error detected in src/BlockHorizons/BlockSniper/ui/window/BrushMenuWindow.php:

Parse error: syntax error, unexpected 'throw' (T_THROW) in src/BlockHorizons/BlockSniper/ui/window/BrushMenuWindow.php on line 47
Errors parsing src/BlockHorizons/BlockSniper/ui/window/BrushMenuWindow.php
```

referring to https://github.com/dktapps-pm-pl/BlockSniper/blob/4aba4b88e662e7b57491faa7320aa73ce0e524cc/src/BlockHorizons/BlockSniper/ui/window/BrushMenuWindow.php#L47

This is valid code in PHP 8.0+, since `throw` is now an expression rather than a statement.

**Comment by SOF3** [comment]
Yes, it's still running on PHP 7.4 because I can't figure out how to upgrade the docker image to 8.0 :(

I'm wondering if it's better to run the PHP lint in a docker container so that we don't have to upgrade the whole poggit.

**Comment by dktapps** [comment]
That would seem like the obvious solution. I had a similar problem with Jenkins recently because the default base image is 5 years old. We ended up moving all jobs into a dedicated agent with a different, newer image.
