### ISSUE TITLE
Problem with the search bar

### ISSUE THREAD

**Issue by NhanAZ** [poggit/poggit#295]
When you search for SkyBlock on poggit you will be redirected to the link
https://poggit.pmmp.io/p/SkyBlock/3.0.0
I think instead of directing users to the above link, they should be redirected to:
https://poggit.pmmp.io/plugins?term=SkyBlock
Because there's not just a single SkyBlock plugin
If the user doesn't know how to edit the link, they only get one result when they search for SkyBlock
Suppose there are 2 plugins with the same name but completely different functions?
I think you should reconsider this issue :3

**Comment by JaxkDev** [comment]
reference, https://github.com/poggit/poggit/blob/c7a9c610f953d9de62e43db230fafbed2d06447f/assets/incl/searchbar.php#L24 changing to `plugins?term=` will probably do the trick.

**Comment by NhanAZ** [comment]
> reference,
> 
> https://github.com/poggit/poggit/blob/c7a9c610f953d9de62e43db230fafbed2d06447f/assets/incl/searchbar.php#L24
> 
> changing to `plugins?term=` will probably do the trick.

I think it should be
