### ISSUE TITLE
There must be at least 1 producer! error when submitting https://poggit.pmmp.io/ci/pmmp/BasicSpawnProtection/~

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit#297]
There is already a producer (me) but it's not happy.

Maybe because the repo is owned by an organization?

**Comment by JaxkDev** [comment]
I can't reproduce on any of my existing / new org projects.

Note this is a client side bug for some reason it wasn't validating the user with github (could potentially have been during github down time or ISE 500 returns) if not validated at client side with github it wont be sent to poggit hence 0 producers.

**Comment by JaxkDev** [comment]
Can't reproduce, and not seen this issue pop up again from anyone most likely just GitHub being funny/down during the time your plugin was updated to new format for producers/authors.
