### ISSUE TITLE
"Release" menu shown on the CI page for virions, but with no selectable options in the dropdown

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit#298]
maybe just change it to a simple button?

**Comment by JaxkDev** [comment]
You cant ‘release’ virions like plugins there is no submission form etc.
That entire column should be removed on virion projects

**Comment by dktapps** [comment]
Yeah I know. But for the plugin case I've also never seen a case where it has anything but "Submit", so it seems pointless to have a dropdown at all.

**Comment by JaxkDev** [comment]
Yeah probably planned feature of something but no trace of anything like that, right now its only submit/update/empty https://github.com/poggit/poggit/blob/4f5538fbfd218c9aec3e6d3a4dd1dfb786342af9/js/ci.project.js#L303-L307
Will change to button unless @SOF3 objects with something

**Comment by dktapps** [comment]
Seems like `Submit` would cover all cases anyway.

**Comment by JaxkDev** [comment]
Couldn't do submit by itself due to URL redirection requiring both submit and update but I think I implemented what you wanted, have a look once @SOF3 pulls.

**Comment by SOF3** [comment]
> Yeah probably planned feature of something but no trace of anything like that, right now its only submit/update/empty
> 
> https://github.com/poggit/poggit/blob/4f5538fbfd218c9aec3e6d3a4dd1dfb786342af9/js/ci.project.js#L303-L307
> 
> 
> Will change to button unless @SOF3 objects with something

Originally there's supposed to be a delete button too, but turns out we didn't want it.
