### ISSUE TITLE
Build passes with incorrect version of virion for API

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit#299]
https://poggit.pmmp.io/ci/dktapps-pm-pl/pmforms-demo/pmforms-demo/dev:4

This build requires API 4.0.0, but used pmforms 1.0.0 (which doesn't support API 4.0.0), and yet the build passed with no errors.

**Comment by dktapps** [comment]
It turns out that the plugin was actually requiring 3.7.2, but in that case, this build should have failed due to using a PM4-only virion: https://poggit.pmmp.io/ci/dktapps-pm-pl/pmforms-demo/pmforms-demo/dev:5

**Comment by JaxkDev** [comment]
https://github.com/poggit/poggit/blob/f23e84481be96dbbe3831080f1989c5db71239e1/src/poggit/ci/Virion.php#L160

Note to self: Just need to get a reference / fetch the plugins API range so that todo can be resolved with a simple semver comparison.

**Comment by JaxkDev** [comment]
@dktapps @SOF3 

So I did have a patch for this locally but my comments have reminded my why I haven't fixed it.

In this scenario:
plugin.yml
```yml
virion: v1.0
api: [3.0.0, 4.0.0, 5.0.0] (or similar)
```

virion.yml (v1.0 - build 1):
`api: 3.0.0`

virion.yml (v1.0 - build 2):
`api: 4.0.0`


which virion should be injected, and then what about 5.0.0 etc.
theres a quite a few quirky cases here


My view is the virion api(s) would have to satisfy _every_ api listed in plugin.yml to be injected?

**Comment by SOF3** [comment]
Dependency resolution is complicated indeed. Pushing for virion v3 is probably the easier solution.
