### ISSUE TITLE
Redirect https://poggit.pmmp.io/ci/author/repo to author/repo/~ directly if there's only 1 project in a repo

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit#300]
In many cases plugins have a whole repo to themselves, in which case the CI project list page is just a pointless extra click.

For example: https://poggit.pmmp.io/ci/dktapps-pm-pl/pmforms-demo is redundant; I'd rather be directed directly to <https://poggit.pmmp.io/ci/dktapps-pm-pl/pmforms-demo/~>, which is where the real meat is.

It's also not obvious where I have to click to get to the actual builds from the projects list page.

**Comment by dktapps** [comment]
was the fix for this pushed to prod yet?

**Comment by SOF3** [comment]
Pulled 5 seconds ago
