### ISSUE TITLE
Virion shading does not properly check for namespace match

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit#301]
This was discussed here: https://discord.com/channels/373199722573201408/708328556064931892/916451917209698395

TLDR: Things in namespace `dktapps\pmforms_demo` get shaded when `dktapps\pmforms` is used, because the namespace shader does not check if the following character is a `\` (or if it's an exact namespace match).

**Comment by SOF3** [comment]
This shouldn't have happened with PHP 7 since each part is parsed individually. @JaxkDev is it new in the PHP 8 support?

**Comment by JaxkDev** [comment]
This would happen on PHP7, this issue was carried forward to the new PHP8 code as well.

**Comment by JaxkDev** [comment]
And based on this bug being linked to `strpos` I have a feeling `new \dktapps\pmforms\whatever(...);` wont get shaded because the prefix \ means strpos wont be 0 but 1.
