### ISSUE TITLE
Virion CLI requires phar.readonly=0

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#303]
Shading virions indeed requires phar.readonly=0, but it should not be required for running CLI commands only.

**Comment by JaxkDev** [comment]
huh?
What other cli commands are there apart from shading ??

**Comment by SOF3** [comment]
Virions can create a file called `cli-map.json`. Then the virion stub will try to load subcommands specified in cli-map.json if available.

For example https://github.com/poggit/libasynql/blob/master/libasynql/cli-map.json
