### ISSUE TITLE
Do not include rejected or submitted plugins in plugin search

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit#304]
https://poggit.pmmp.io/plugins/called/command

Over half the plugins in this search are rejected. Many more haven't been approved.

This adds a bunch of useless noise to the search. If I want to see submitted plugins I would go to the Review page.

I understand that the reason I see these is because I have reviewer permissions; however, I don't go to the search when I want to review plugins, I do it because I want to _find_ a plugin.

At the least, the search should by default only include released plugins.

**Comment by JaxkDev** [comment]
0444c48b9bc364fb6135101ff17ab2c37aeccead
