### ISSUE TITLE
"poggit build" in commit message may lead to 500ISE

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#306]
https://github.com/poggit-orphanage/PurePerms/commit/a504cbe607fc4400f2aabc63893189a83f4e08ec

```
Level 0: Undefined array key "to get all latest changes" in /poggit/src/poggit/ci/builder/ProjectBuilder.php#170
#0 /poggit/src/poggit/ci/builder/ProjectBuilder.php(170): poggit\error_handler(2, 'Undefined array...', '/poggit/src/pog...', 170)
#1 /poggit/src/poggit/webhook/PushHandler.php(169): poggit\ci\builder\ProjectBuilder::buildProjects(Object(poggit\ci\RepoZipball), Object(stdClass), Array, Array, Object(poggit\ci\cause\V2PushBuildCause), Object(poggit\ci\TriggerUser), Object(Closure), 1, 'master', 'xxx..', true)
#2 /poggit/src/poggit/webhook/GitHubWebhookModule.php(144): poggit\webhook\PushHandler->handle('poggit-orphanag...', 'xxx...')
#3 /poggit/src/poggit/webhook/GitHubWebhookModule.php(66): poggit\webhook\GitHubWebhookModule->output0('poggit-orphanag...', 'xxx...')
#4 /poggit/src/poggit/Meta.php(212): poggit\webhook\GitHubWebhookModule->output()
#5 /poggit/entry.php(50): poggit\Meta::execute('webhooks.gh.rep...')
#6 /var/www/html/index.php(23): include('/poggit/entry.p...')
#7 {main}
```

**Comment by JaxkDev** [comment]
Bit unsure how to change this behaviour, its looking for a keyword after `poggit build` like all / none / nil or the project name...
Do we build all the projects if none of those are met ? (string after `poggit build` is not a keyword/known project name)


https://github.com/poggit/support/blob/4c0e5285eb72e9acb94b7d0e375ae3cc9c42cc8e/poggit.yml.d.ts#L21
https://github.com/poggit/poggit/blob/b1c897207a5e95c9fe43a67b256f8f24c6fb898e/src/poggit/ci/builder/ProjectBuilder.php#L232-L257

**Comment by JaxkDev** [comment]
@SOF3
> Do we build all the projects if none of those are met ? (string after poggit build is not a keyword/known project name)

**Comment by SOF3** [comment]
@JaxkDev I think nobody knows this black magic behavior anyway. what about we just remove it? 🙃

**Comment by JaxkDev** [comment]
> @JaxkDev I think nobody knows this black magic behavior anyway. what about we just remove it? 🙃

Okay, will strip out the optional argument after `poggit build <project>` and `skip <project>` and assume all projects.
