### ISSUE TITLE
Be more consistent with github button placements

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit#307]
![image](https://user-images.githubusercontent.com/14214667/147600452-6d9d9017-dd99-40b5-8232-ea670d07b7ac.png)

This always confuses me. There is a button that goes to the user's github profile but not one to go to the source code.

Meanwhile, on the plugin's release page, it's the other way round: 
![image](https://user-images.githubusercontent.com/14214667/147600525-bea40bbd-1c7f-47a9-a62a-a8ebb6087677.png)

**Comment by JaxkDev** [comment]
May be other places but thats those two added, can now go straight to author on release page & straight to repo on project CI page

**Comment by dktapps** [comment]
I guess this wasn't deployed yet.

**Comment by JaxkDev** [comment]
@SOF3

**Comment by SOF3** [comment]
Pulled
