### ISSUE TITLE
"Release Search" Problem

### ISSUE THREAD

**Issue by NhanAZ** [poggit/poggit#310]
# Steps to reproduce the problem:
~~https://youtu.be/4LRQpooOXC0~~ (Video has been deleted)
1. Search something on the release search bar (Ex: skyblock)
2. Click the "Search" button
3. Keep searching for something else on the release search bar (Ex: myplot)
4. Click the "Search" button

After performing step 4, no results will be returned

**Comment by JaxkDev** [comment]
Not fixed.
Different error has occurred, something to do with the plugin API's array being null when being sorted/listed so search stuff after is never reached due to errors.
