### ISSUE TITLE
Problem with query bar

### ISSUE THREAD

**Issue by NhanAZ** [poggit/poggit#311]
Can't query plugins with API < 4.0.0

![image](https://user-images.githubusercontent.com/60387689/158563449-cacae56a-f732-4c58-91f2-9389568dff0b.png)

**Comment by SOF3** [comment]
you need to add `?outdated` to the URL. this is a usability issue indeed.

**Comment by NhanAZ** [comment]
> you need to add `?outdated` to the URL. this is a usability issue indeed.

Thanks. It works for me. But I think the query bar should still be considered fixed.
