### ISSUE TITLE
Argo Tunner Error

### ISSUE THREAD

**Issue by xRodzMC** [poggit/poggit#314]
Dear @poggit, 
# Issue
When you visit [poggit.pmmp.io](https://poggit.pmmp.io) it will shown cloudflare agro tunner error. 

# Error 1033
## What happened?
You've requested a page on a website ([poggit.pmmp.io](https://poggit.pmmp.io)) that is on the [Cloudflare](https://www.cloudflare.com) network. The host ([poggit.pmmp.io](https://poggit.pmmp.io)) is configured as an Argo Tunnel, and Cloudflare is currently unable to resolve it.

# What can I do?
**If you are a visitor of this website:**
Please try again in a few minutes.
**If you are the owner of this website:**
Ensure that cloudflared is running and can reach the network. You may wish to enable [load balancing](https://developers.cloudflare.com/argo-tunnel/reference/load-balancing/)  for your tunnel. 

# Pleasure
Please fix this issue at your argo tunnel. It may cause system lose of data from plugins. 

# Guide
You can enable [load balancing](https://developers.cloudflare.com/argo-tunnel/reference/load-balancing/) on your tunnel.

<hr>
<p align=right>
Regards, @xqwtxon <3
</p>

**Comment by SOF3** [comment]
Please don't report server downtime on the GitHub issue tracker. The issue tracker is for tracking code issues not operation issues.

**Comment by xRodzMC** [comment]
Dear @SOFe, 

You can make your own maintenance mode for people didnt know, what is problem or being maintenance mode. 
**TIP:** You can make your own http error pages, as i know. 

<p align=right>
Regards, @xqwtxon <3
</p>

**Comment by SOF3** [comment]
the best maintenance page is a poggit site that works.
