### ISSUE TITLE
Add an api getter for latest dev builds without providing a commit hash or resource id input

### ISSUE THREAD

**Issue by xBeastMode** [poggit/poggit#318]
Add a way to get latest dev builds without giving commit hash or resource id input. Just like you can do with `poggit/get/plugin-name`, add `poggit/build/author/repository` which throws the phar automatically. This could be useful for things such as adding a github workflow that uploads a release asset, instead of having to build the release manually from the workflow: you have to also manually update virions in the workflow, which can give room for vulnerabilities in virions if not updated to latest version and it's gets tedious having to maually update them on workflows. This can all be evaded with my suggestion above.

**Comment by SOF3** [comment]
yes, I would like to add such an API too. just need more slaves for that.

**Comment by JaxkDev** [comment]
see `poggit/get/plugin-name/dev` for now

**Comment by JaxkDev** [comment]
`poggit/build/author/repository` alone won't suffice due to multiple projects in a single repo (hence the virion naming being `author/repo/project`) but I'm still a little confused, for plugins you can use the above (`poggit/get/plugin-name/dev`) for virions I'll have to check and come back to you

**Comment by SOF3** [comment]
/v.dl/:owner/:repo/:project/:semver

**Comment by SOF3** [comment]
the /get/plugin-name/dev looks up the unique release name from the released plugin list. the dev build is retrieved from the repo used to release the plugin.

**Comment by JaxkDev** [comment]
could add `p.dl` with same parameters as `v.dl`

**Comment by SOF3** [comment]
Isn't `/get` sufficient?

**Comment by SOF3** [comment]
Sure, if anyone wants to implement it. But plugins do not have the semantic versioning like virions do, so the mechanism is slightly different (but probably even simpler).

With that effort though, perhaps it's easier to just write a GitHub workflow to stage the phar to the repo's GitHub pages?

**Comment by JaxkDev** [comment]
> Sure, if anyone wants to implement it. But plugins do not have the semantic versioning like virions do, so the mechanism is slightly different (but probably even simpler).
> 
> With that effort though, perhaps it's easier to just write a GitHub workflow to stage the phar to the repo's GitHub pages?

I was thinking either specifying `dev` or version to download instead of semver

**Comment by SOF3** [comment]
Downloading a version doesn't make sense. If it is versioned, it is already released.

**Comment by JaxkDev** [comment]
> Downloading a version doesn't make sense. If it is versioned, it is already released.

Yeah true, `get/` already exists for released plugins

**Comment by JaxkDev** [comment]
So I’m thinking `p.dl/author/repo/project/?buildId` (option BuildId otherwise latest dev)
