### ISSUE TITLE
jquery.com having a bad day, all requests taking forever

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit#320]
`GET https://code.jquery.com/ui/jquery-ui-git.css net::ERR_CONNECTION_TIMED_OUT`

Perhaps we can replace this with a Google mirror?

**Comment by SOF3** [comment]
Aren't we already using ajax.googleapis.com?

**Comment by JaxkDev** [comment]
Yes for script but theres still a direct one here for the stylesheet
 https://github.com/poggit/poggit/blob/7a43b3386344b27d494c5eb269b7df53639dc3ec/src/poggit/module/HtmlModule.php#L71

**Comment by JaxkDev** [comment]
I'm baffled, including the same file twice? (one locally hosted, one off google api)
    
```
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="<?= Meta::root() ?>js/jquery-ui.min.js"></script>
```


Nevermind, seem that witchcraft is only for `release.flow` modules.
