### ISSUE TITLE
src-namespace-prefix in PHPStan and lint

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit#322]
Why is this still not supported?

**Comment by JaxkDev** [comment]
Which bit’s specifically?
PHPStan I can’t update right now, and as far as I remember original poggit lints were updated when PM4 came out

**Comment by JaxkDev** [comment]
Might break PM5+ should probably go back and fix the duct tape I used…
https://github.com/JaxkDev/poggit/blob/c0fb9b3bddbeb494e7df730f57dc65164ab4ae69/src/poggit/ci/builder/DefaultProjectBuilder.php#L143

**Comment by dktapps** [comment]
The problem likely comes from here: https://github.com/poggit/poggit/blob/a799c731086b3cc0141057ee58d3563afc152838/src/poggit/ci/builder/ProjectBuilder.php#L554

I encountered it with dktapps-pm-pl/ClientConsole.

**Comment by dktapps** [comment]
> Might break PM5+ should probably go back and fix the duct tape I used… https://github.com/JaxkDev/poggit/blob/c0fb9b3bddbeb494e7df730f57dc65164ab4ae69/src/poggit/ci/builder/DefaultProjectBuilder.php#L143

I see, seems like this check appears in a few places. Problem showed up with a PM5 plugin, I assumed it had never been fixed.

**Comment by dktapps** [comment]
Fixed by 6b375da14e1552b9335adc655dda0a3d68bc11f4
