### ISSUE TITLE
Extract Virion Injector

### ISSUE THREAD

**Issue by JaxkDev** [poggit/poggit#326]
Currently each virion has their own built in injector (at the time of build).

This becomes problematic when old virions that do not require updating at all will still have ancient/old injector versions

Such as v1.5 includes the PM4 support for src-namespace-prefix but virion builds older than roughly Feb 2023 won’t have this version and will NEVER be injected with src-namespace-prefix support.

Having a standalone injector script to inject a virion into plugin means poggit will be able to inject any virion build with the latest injector code.

**Comment by SOF3** [comment]
The injection script in Poggit only implements the virion v1 spec, which is in LTS stage now. The semi-official implementation of virion v3 spec is in pharynx, which is already a standalone tool.

**Comment by dktapps** [comment]
v1 is still going to be used for some time though, so this issue should be addressed.

**Comment by JaxkDev** [comment]
Correction: Poggit itself uses the latest injector regardless of virion stub, therefor this issue is only present for users who download virions and use the stubs of the old virions to inject.

**Comment by dktapps** [comment]
does anyone actually do that?

**Comment by JaxkDev** [comment]
> does anyone actually do that?

Not a scooby.

**Comment by JaxkDev** [comment]
Development cost outweighs benefits now.
(I hate virions, anyone else is welcome to make their own standalone script)

**Comment by SOF3** [comment]
Let's just push for adoption of virion v3. Building virions as phars is stupid indeed.
