### ISSUE TITLE
Support for duplicate plugin names

### ISSUE THREAD

**Issue by NhanAZ** [poggit/poggit#331]
as the title

**Comment by JaxkDev** [comment]
Definitely not, we purposely fixed a bug that meant users could submit plugins with the same name.

The whole Poggit infrastructure would require changing to support same name plugins.

**Comment by SOF3** [comment]
We could *consider* duplicate plugin.yml names with different release names, but imo that makes the entire supply chain much more complicated for everyone. Better just rename your plugin to something like `PluginName-AuthorName` if it is a duplicate. Or just find a better name.

**Comment by SOF3** [comment]
There can't be more poggit plugins than npm packages. If npm found their way out of this, no way we can't :)
