### ISSUE TITLE
RFC - Overwriting plugin manifest details on release

### ISSUE THREAD

**Issue by JaxkDev** [poggit/poggit#335]
Currently (better known recently) poggit will overwrite the following details in plugin.yml with details from submission form:

- name
- version
- api
https://github.com/poggit/poggit/blob/db24acddb9b9e99478be8e88b8401375a59570e7/src/poggit/release/submit/PluginSubmission.php#L297-L301

This creates a lot of inconsistency between source code written and the plugin being distributed.
for example:

- different name results in different plugin_data path (and therefor disregarding data) if it changes on next form etc.
- different name may result in permission names not actually being prefixed with runtime plugin name.
- different version from source code may result in problems reporting bugs etc.

I personally don't think poggit should be overwriting anything, that being said this change should also result in the following details from the submission being made read-only to avoid "false advertising" as such.
- name
- api
- version

with those details being read-only from plugin manifest, and any change should come from a new build with the relevant changes.

**Comment by dktapps** [comment]
Yes

**Comment by JaxkDev** [comment]
~~Seems `API` is very much linked into poggit way more then I would have liked, for now I've worked on `name` and `version` being read-only with `API` following pending some investigations into what may break and how to deal with that.~~
