### ISSUE TITLE
Missing Access-Control-Allow-Origin (CORS) Header

### ISSUE THREAD

**Issue by soyilai** [poggit/poggit#337]
Poggit does not set the `Access-Control-Allow-Origin` header in its response. As a result, it's impossible to make requests to the API from another website due to the same-origin policy enforced by web browsers.

**Comment by SOF3** [comment]
for the record, CORS is only reasonable for the releases.json endpoint. other endpoints should not be allowed for external domains.

**Comment by JaxkDev** [comment]
I assume a simple `Access-Control-Allow-Origin: *` header in the releasesjson module should suffice ?
