### ISSUE TITLE
Plugin description renderer broken

### ISSUE THREAD

**Issue by DiarDev** [poggit/poggit#343]
Error in arranging items ##, its format error instead of dividing the items into a vertical line down, most developers were very upset with this problem and reported many time!
I hope poggit fixes this issue as quickly as possible because most devs have been upset and reported this issue many times! Thank.

**Comment by JaxkDev** [comment]
Issue is GitHub has changed the response and so we have ALL the plugins pre whenever this started with the old format, and now every plugin since with the new format.

I can't work on fix until we can get the changes between old and new responses.

https://api.github.com/markdown
