### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mrchlldev** [poggit/poggit#355]
500 Internal Server Error
A server internal error occurred. Please use this request ID for reference if you need support: 0b5c-8b40b436402da3f2-SIN

**Comment by JaxkDev** [comment]
As a very quick try and see
I can see your icon has brackets in the name, can you try a simpler icon
file name with no special chars eg ‘icon.jpeg’ ?

But thats the only off thing I can see briefly looking at half the error log

**Comment by JaxkDev** [comment]
No-reply, auto closing.
