### ISSUE TITLE
API endpoint to list releases returns blank page

### ISSUE THREAD

**Issue by JulianVennen** [poggit/poggit#356]
Going to https://poggit.pmmp.io/plugins.json or https://poggit.pmmp.io/plugins.min.json results in a completely blank page. 
Searching for a specific plugin works though: https://poggit.pmmp.io/plugins.min.json?name=sheep

```
> GET /plugins.json HTTP/2
> Host: poggit.pmmp.io
> User-Agent: curl/8.6.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200 
< date: Wed, 04 Sep 2024 11:20:17 GMT
< content-type: application/json
< content-length: 0
< cf-ray: 8bdd96dec9067163-DUS
< cf-cache-status: DYNAMIC
< access-control-allow-origin: *
< x-object-count: 4771
< x-poggit-request-id: dbc7-8bdd96ded5bf7163-DUS
< x-powered-by: PHP/8.0.30
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=Zin8iyg45nGq7HEaIRTs2wtDnK%2BiLSGST7pmODTSj1OjXVPW3pRRZA5uHZA2DO7w3rIYmgmsyAQ3KELxWMXf9nl0Lbm%2F5Rgb2Nt8R5prveHu%2BodOiNb2v3WbVPVmdkRKgVF%2FaZKK6o4wDHhBAw%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< alt-svc: h3=":443"; ma=86400
< 
```

I found a similar issue where the non-minified version was causing the same problem here: https://github.com/poggit/poggit/issues/321
Unfortunately, the issue appears to affect both endpoints now.

**Comment by JulianVennen** [comment]
It also seems like setting the `latest-only=on` query parameter solves the issue, so maybe it's related to the response length?

**Comment by JulianVennen** [comment]
Any updates on this?

**Comment by JaxkDev** [comment]
> Any updates on this?

I remember this being mentioned maybe in discord or another issue, but I can’t help much since this is production specific.
You’ll have to bug @SOF3 to investigate.

**Comment by JulianVennen** [comment]
Hey @SOF3 could you look into this please?

**Comment by SOF3** [comment]
Did a bit online debugging, the problem seems to lie in possible overflow or otherwise unexpected process abort during `echo` of the json object, presumably due to `OutputManager` issues.

ReleastIndexJsonModule does not require output buffering, and thus can be disabled. Pull requests are welcome.

**Comment by SOF3** [comment]
BTW, it would also be useful to add a `releases.jsonl` endpoint that returns the result in [JSONLines format](https://jsonlines.org) instead. This would facilitate optimizations on the client side as well.

**Comment by JulianVennen** [comment]
Are these changes not deployed to poggit.pmmp.io yet, or is there something wrong with them?
This issue still occurs, and the jsonl endpoint I added also isn't there.

**Comment by SOF3** [comment]
not yet, I'll try to remember to do it this weekend
