### ISSUE TITLE
Count downloads of each build

### ISSUE THREAD

**Issue by Dog2puppy** [poggit/poggit#37]
I think it would be cool if poggit showed how many times each build was downloaded. And then on the project page it would show the total downloads.

**Comment by Awzaw** [comment]
Download counts will be displayed in the 'Release' section, but not for CI as that is NOT a plugin list

**Comment by AmiroEmad** [comment]
Supported

**Comment by Awzaw** [comment]
Hi Amir - 'Supported'?!

**Comment by AmiroEmad** [comment]
@Awzaw I was just supporting the suggestion.

**Comment by Awzaw** [comment]
Ah ok - we all love download counts ;-) When Release is done, you'll see them there
