### ISSUE TITLE
Echo on Async tasks

### ISSUE THREAD

**Issue by Ad5001** [poggit/poggit#38]
Hello,

*Please note that I can't know if this is considered as a bug. It can be an enhancement*

Recently, I made some plugins with async tasks (I won't give it's name thought it won't be approved) and I noticed that when echoing, we get a lint error. For a normal sync file, I fully understand.

But what about asyncs tasks? We cannot call the PM logging function due to being async so we need to use echo with our own logging system. I think there that it should not emit a lint.

**Comment by SOF3** [comment]
It is pretty impossible to prevent this. We don't know in what thread will a function be executed in. Even professional IDEs rely on annotations or doccomments to indicate whether a function is executed in a certain thread. (See Android's `@UiThread`/`@WorkerThread` annotation)

Note the recent addition of the `AsyncTask::publishProgress()` function, which can be used for executing code on the main thread initiated in async tasks.

Also note that AsyncTask is intended to be executed for a short period, so it is somehow redundant to show messages.

**Comment by SOF3** [comment]
You can create a new issue for the feature addition of lint suppression symbols in code.

**Comment by Ad5001** [comment]
I know that is impossible. But like when executed on a class having "extends AsyncTask " is impossible to detect? I didn't looked into your syntax checking yet.

**Comment by SOF3** [comment]
@Ad5001 Poggit only has primitive token-based checking right now. Not even detecting functions, although detecting class names already.

I think for your case it is best to use publishProgress() and use getLogger()->info() in the onProgressUpdate() function.

**Comment by SOF3** [comment]
Moreover, I consider it to be low-quality code to use `extends AsyncTask` as the indicator, since main thread code can be in AsyncTask class files and async code can even be in the main class.

**Comment by Ad5001** [comment]
True...
