### ISSUE TITLE
Suggestion: Make poggit logo redirect to Home page.

### ISSUE THREAD

**Issue by Sandertv** [poggit/poggit#42]
Thanks for putting hours of work in Poggit, it's starting to become something absolutely amazing! There is one thing I'd like to ask if you could add that, which I don't think is too hard to do. Do you think it would be a good idea to make the Poggit logo on the top left corner redirect you to the home page when clicking it? No problem if you don't like the idea. I just feel like it makes the website even better!

Anyways, keep up the great work!

**Comment by Sandertv** [comment]
Thank you @Awzaw!

**Comment by SOF3** [comment]
Would be great if this includes the `Poggit` word too, as well as that on mobile site.
