### ISSUE TITLE
Clicking problem with navbar

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#43]
Navbar refers to navtabs i.e. `Home` `CI` `Release` `Help`.

While the cursor is `hand` for the whole navtab, only the words are clickable (as an `<a>`). This is especially notable in mobile, where the whole area with `hand` cursor gets highlighted, and people don't understand why the links won't work.

**Comment by Awzaw** [comment]
It's on my long list!

**Comment by Awzaw** [comment]
Done
