### ISSUE TITLE
Search bar directs to wrong plugin version

### ISSUE THREAD

**Issue by Sandertv** [poggit/poggit#44]
When using the search function, it does not seem to direct to the latest version of the plugin that was searched. I'm not sure if this is because I used a weird version (0.0.99), but I think that should not work like that.

How to reproduce?
1. Go to Poggit and type BlockSniper in the search bar. Sorry if this is considered advertising, it isn't meant to be.
2. Poggit will direct you to version 0.0.99. The latest version however is version 2.0.0.

**Comment by Awzaw** [comment]
Thanks for pointing it out, should be fixed today

**Comment by Sandertv** [comment]
Thank you!
