### ISSUE TITLE
Associate releases

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#45]
Some plugins, like @onebone's Economys plugin, have multiple phars but are released together as addons. Poggit should add an option "Associate release" such that a release is associated with the main project.

Required for releasing plugins like EconomyS

===

Update as of August 2017: Still need to add a button to download an archive containing all associated plugins.

**Comment by Awzaw** [comment]
I can't see much difference between an "optional dependency", whatever that is exactly... and an "associate release", except that maybe the latter would be reserved for plugins from the same author. So do we need a separate section for this, or could we add a third category such as "Associated Plugin" to Required/Optional?

**Comment by SOF3** [comment]
Associated releases are actually packages of plugins. Dependencies are just "You can use them together" "It's an add-on", but association is stronger -- "You SHOULD use them together". Therefore there should be a zip download for associated projects while this is not needed for normal dependencies.

**Comment by SOF3** [comment]
In simple words, "Foo depends on Bar" vs "Foo is an associate of Bar":

| Dependency | Association |
| :---: | :---: |
| Both Foo and Bar are listed in /pi | Foo is not listed in /pi. Only Bar is listed in /pi. |
| Foo and Bar are downloaded separately | Bar's download button should link to a zip containing both Bar.phar and Foo.phar, with smaller buttons displaying individual phar downloads for both Bar.phar and Foo.phar |
| In /p/Foo, Bar is displayed in a medium box called "Dependencies" at the top | In /p/Foo, the plugin name is displayed as "Bar > Foo" in a way such that it looks like Foo is a component in the Bar plugin. |
| In /p/Bar, Foo is displayed in a small box called "Dependents" at the bottom (similar to "Users also install" in Google Play) | In /p/Bar, Foo's description is displayed in a spoiler immediately after the description of Bar itself. |

**Comment by Awzaw** [comment]
Got it :-)

**Comment by Awzaw** [comment]
"Foo is not listed in /pi. Only Bar is listed in /pi"
How do you suggest we manage an associated Foo's release status? It should presumably be >=approved to qualify as an associated plugin, and yet we don't want it in /pi; a new 'parent_releaseId' column in releases?

**Comment by SOF3** [comment]
Yeah, that's a good way.

**Comment by Awzaw** [comment]
Do we allow multiple parents? I've started with only one... and I'm assuming users can only associate their own plugins.

**Comment by SOF3** [comment]
Yet. Also, a parent release must not be the child of another.

**Comment by SOF3** [comment]
Yep*

**Comment by Awzaw** [comment]
Was that a 'yep' for multiple parents too? I'm hoping not...

**Comment by SOF3** [comment]
Yep for only associating own plugins.
Parent plugin + children plugins = one package. It doesn't make sense to add your plugin into others' package, or to have multiple "main" plugins in the same package.

**Comment by SOF3** [comment]
Should be replaced by a Plugin Lists mechanism
