### ISSUE TITLE
Keywords stack when releasing

### ISSUE THREAD

**Issue by Sandertv** [poggit/poggit#46]
When releasing, the searching keywords at the bottom of the page appear correctly, but when submitting an update the keywords get added again, next to the already existing keywords. This causes a long string of the same keywords, which can be seen at the bottom of the page here: https://poggit.pmmp.io/p/BlockSniper/45. 

Steps to reproduce:
1. Release a plugin of any kind.
2. Submit a plugin update and don't change the keywords.

**Comment by Awzaw** [comment]
working on that as I found this :-)
