### ISSUE TITLE
Releasing a new plugin version, and removing the old version will clear all reviews

### ISSUE THREAD

**Issue by Sandertv** [poggit/poggit#53]
When submitting a new release to Poggit, and removing an older release of that plugin, on which the review has been made in the first place, the reviews from that version will be cleared.

How to reproduce?
1. Leave a review on your plugin.
2. Submit a plugin release for that plugin.
3. Remove the old version.
4. Check the review page again.

I'm not entirely sure if this is intended or not. If it is, feel free to close this.

**Comment by SOF3** [comment]
Why do you remove the old version anyway?

**Comment by Sandertv** [comment]
Erm, blame me for reading something wrong.

**Comment by SOF3** [comment]
Actually I wonder whether older versions should be allowed to be deleted at all. It only makes sense to delete the old plugin, but not to delete older versions.

**Comment by Sandertv** [comment]
In addition to this, having submitted an update for a plugin in the same situation as above but not removing the old version, will make the review not show up in the newest version.

**Comment by Thunder33345** [comment]
but if you choose not to release eventually we will end up with bunch of old CI build and bunch of old releases which would take up disk space

and i propose to demote plugin stats to a new updated-unchecked status since it can potentially be abused to inject code without reviewers notice

**Comment by Awzaw** [comment]
You could inject code? Where?

**Comment by Thunder33345** [comment]
@Awzaw i am suspecting
if i submitted A plugin and if it gets approved, i can update it without having reviewer re check the code, or that's what i expect it to behave like which i could be wrong

**Comment by Sandertv** [comment]
@Thunder33345 it does have to be re-checked before showing up.

**Comment by SOF3** [comment]
Forwarding this in case you don't check. @Thunder33345 
![screenshot_2017-02-28-22-23-22](https://cloud.githubusercontent.com/assets/19623715/23408922/a90047e2-fe04-11e6-95ee-cd7ed76c9475.png)

**Comment by Thunder33345** [comment]
@SOF3 typo i meant old
but i think we should start archiving before it gets to be a problem, like only serve 100 lattes builds

**Comment by Awzaw** [comment]
If you mean reviews, at the moment they are per release, not per project, so if you release a new build it a) needs reapproval and b) currently only shows reviews for that version. I'll change that to show reviews for earlier releases too, and we are going to revamp reviews soon

**Comment by Sandertv** [comment]
Just thought it was a bit weird that the (for example) 5/5 DOES show up in the corner of the release.

**Comment by Awzaw** [comment]
I wouldn't have expected that... maybe I already changed scores to take into account all reviews per project  and there might be some orphaned reviews, I'll check

**Comment by SOF3** [comment]
Does this issue persist?

**Comment by SOF3** [comment]
Is still issue still valid?

**Comment by Sandertv** [comment]
I can't tell, as none of my plugins have any reviews.  (anymore)

**Comment by robske110** [comment]
As far as I know one can't delete old releases anymore, rendering this issue invalid. Or am I wrong about that?

**Comment by SOF3** [comment]
Closing as obsolete.
