### ISSUE TITLE
Cannot submit plugin update

### ISSUE THREAD

**Issue by ivand-sykt** [poggit/poggit#55]
![image](https://cloud.githubusercontent.com/assets/8011308/23330358/002ae95a-fb5d-11e6-9575-97532ef08ac9.png)
This happens in console after clicking "submit update". Only button becomes strikedthrough.

**Comment by Awzaw** [comment]
Should be fixed now, can you test again please?

**Comment by ivand-sykt** [comment]
@Awzaw fixed! thanks!
