### ISSUE TITLE
Spam project creation from lag

### ISSUE THREAD

**Issue by jasonw4331** [poggit/poggit#60]
If I click the confirm button when adding a repo to poggit more than once before it closes the window, it spams adding the repository to poggit.

![Glitch 1](http://imgur.com/T5aPqru.png)
![Glitch 2](http://imgur.com/NdpaezM.png)

**Comment by SOF3** [comment]
Then why did you click it multiple times in the first place?

Also, the repo boxes on the right are a bit broken when it comes to interactivity. Reload after waiting for several seconds.

**Comment by Thunder33345** [comment]
if it couldnt became a attack vector we shouldn't be too worry

**Comment by jasonw4331** [comment]
I've done that @SOF3 and it removed all of them. The repository wasn't actually added, but the commits still went through.

**Comment by Awzaw** [comment]
Fixed confirm button, added info when adding a repo

**Comment by Awzaw** [comment]
The repo should still have been added once even though the info boxes were empty - if not that's maybe a separate issue

**Comment by jasonw4331** [comment]
Yea, the switch on the side is marked as off. And it doesn't appear to be on any other list.

**Comment by Awzaw** [comment]
What do you see now when you enable?

**Comment by jasonw4331** [comment]
![Glitch 1](http://imgur.com/5Dvizvi.png)
![Glitch 2](http://imgur.com/YKASnoM.png)
![Glitch 3](http://imgur.com/Fy8tj5B.png)

**Comment by Awzaw** [comment]
If it's for https://github.com/jasonwynn10/GlowstoneCircleWorld master branch, it's empty...

**Comment by jasonw4331** [comment]
Shouldn't it still be added though? I am still planning on making it a plugin.

**Comment by Awzaw** [comment]
Much as I'd love that to be possible, Poggit can't build anything until the code is there!

**Comment by jasonw4331** [comment]
What if there was a queue for the empty repositories that haven't been added to yet? Could it remain in the  list even though it had nothing to compile?

**Comment by Awzaw** [comment]
I don't think so, why would you want it on Poggit before it can be built?

**Comment by jasonw4331** [comment]
Personally, I would just like it there as a reminder of what to work on, but that's a good point

**Comment by SOF3** [comment]
Poggit managed plugins in a project-based approach. Repos are only a level of communication between GitHub and Poggit, and for grouping projects. If there are no projects, there is nothing to display at all.
As you can see, there is almost nothing in common between builds due to the same commit. This is because Poggit considers them as entirely separate builds. Whether you have commits in non-project files has nothing to do with Poggit.
