### ISSUE TITLE
How do you use the API?

### ISSUE THREAD

**Issue by TheDiamondYT1** [poggit/poggit#61]
Heyo.

Im making an app and a plugin which requires the poggit api, but i have no idea how to use it.
`https://poggit.pmmp.io/api` shows "Invalid JSON string".

Basically all i need to do is list the plugins, get individual plugin info and get the plugin download link via the api.

**Comment by SOF3** [comment]
Far from completing. Still in the design stage, not even in implementation stage.

**Comment by SOF3** [comment]
For further questions, please use poggit/support instead.
