### ISSUE TITLE
Downloads reset on meta update

### ISSUE THREAD

**Issue by ivand-sykt** [poggit/poggit#64]
Downloads count on release resets after updating metadata of release (downloads from older versions (draft) are not reset).

Steps to reproduce:
1. Make you plugin downloaded a few times.
2. Update plugin description.
3. View at release downloads count.

**Comment by Awzaw** [comment]
Thanks, fixed

**Comment by ivand-sykt** [comment]
and who will restore missing downloads? :D

**Comment by Awzaw** [comment]
gone forever I think :-(
