### ISSUE TITLE
Mobile page disorientation

### ISSUE THREAD

**Issue by jasonw4331** [poggit/poggit#65]
This happened on mobile after closing all switch panels
Tested using the iPhone 7
![img_0678](https://cloud.githubusercontent.com/assets/16521025/23712829/0b755186-03f2-11e7-97a9-ff97434cf512.PNG)
![img_0679](https://cloud.githubusercontent.com/assets/16521025/23713054/aee9b528-03f2-11e7-86e9-22a9e9c6a8cb.PNG)

**Comment by jasonwynn10** [comment]
That was taken on my iPhone 7

**Comment by HimbeersaftLP** [comment]
Looks like an iOS only bug, I don't get that bug on Windows Phone and Android

**Comment by Awzaw** [comment]
Do you see the same problem with  Chrome?

**Comment by jasonw4331** [comment]
chrome on ios

**Comment by Awzaw** [comment]
Yes, do you see the same problem using Chrome on the Phone 7

**Comment by jasonw4331** [comment]
That's how i first noticed it.
iPhone 7 regular size
google chrome browser

**Comment by Awzaw** [comment]
Ok, thanks. I think it's related to the ajax loadng the repo data rather than the CSS itself. I'll sort it out today hopefully

**Comment by jasonw4331** [comment]
9877fcc seems to have fixed it
