### ISSUE TITLE
MultiSearch issues

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#67]
1. URLs pointing to the repos instead of projects
2. As the project name is consistent across different builds, it should search projects instead of builds.

**Comment by Awzaw** [comment]
How about switching to AJAX for release search?

**Comment by SOF3** [comment]
Isn't MultiSearch about CI?
About release search by AJAX, it is OK, but make sure we still have a search-within-URL link, in order to keep `/p/invalid-plugin-name` redirect to searching `invalid-plugin-name`.

**Comment by Awzaw** [comment]
Ok, there's still lots to do for CI and release searching, sorting and filtering

**Comment by jasonw4331** [comment]
Should multisearch give more than one build of each project?

**Comment by Awzaw** [comment]
It should now link to the project pages, where you can access all the builds

**Comment by jasonw4331** [comment]
Maybe you can order them with the released plugins first?
