### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Sandertv** [poggit/poggit#68]
When trying to submit a plugin update today, I found myself with a 500 Internal Server Error page. When opening the CI page, it shows the 'release plugin' button, instead of the 'submit build for plugin update'. (or something like that) I think this might be because I've changed the repository to an organization.

Things I have tried:
- [x] Waited for some time, clicked again.
- [x] Re-enabled Poggit-CI for the repository, clicked again.

Neither of both have worked.
I hope you can help me. Thanks!

**Comment by Awzaw** [comment]
Can you try again and give me the error ID?

**Comment by Sandertv** [comment]
Yes sir, the error ID is `69bf-341e79fc2959728f-AMS`

**Comment by Awzaw** [comment]
Can you try again now? should be fixed...

**Comment by Sandertv** [comment]
It works now! Thank you!
