### ISSUE TITLE
Feature Request: Multisearch on the homepage

### ISSUE THREAD

**Issue by jasonw4331** [poggit/poggit#70]
Just for simplicity's sake, can we get a search bar on the homepage or a link to the recent builds? I would rather have a direct link to all of them than to have to scroll down the homepage. Also, it would be nice for when users are logged in with github not to have to go through their own projects to get to the multisearch.

**Comment by Awzaw** [comment]
I can add a link on the Home page, but how about changing the menu CI link to https://poggit.pmmp.io/ci/recent as it is for guests?

**Comment by jasonw4331** [comment]
That would work nicely

**Comment by Thunder33345** [comment]
so guest only?

**Comment by Awzaw** [comment]
I was thinking more along the lines of everyone goes to recent builds at /ci, but only logged in users see the 'My Projects' link, as they do already.
