### ISSUE TITLE
Are the 'Building Repo' tags supposed to be like this?

### ISSUE THREAD

**Issue by jasonw4331** [poggit/poggit#71]
Are these supposed to be stacked or are they supposed to be displayed horizontally?
![screenshot 2017-03-23 at 11 14 19 am](https://cloud.githubusercontent.com/assets/16521025/24255196/27b8f008-0fbb-11e7-8311-ca27c8ab4b4f.png)

**Comment by Awzaw** [comment]
thanks, fixed
