### ISSUE TITLE
I have no idea what happened....

### ISSUE THREAD

**Issue by jasonw4331** [poggit/poggit#72]
![screenshot 2017-03-24 at 1 40 52 pm](https://cloud.githubusercontent.com/assets/16521025/24306624/90970042-1097-11e7-96a1-c4664f71985d.png)

**Comment by Awzaw** [comment]
Are you referring to the alignment of the Recent Releases boxes, or that you have logged out?

**Comment by jasonw4331** [comment]
The box alignment after logging out

**Comment by Awzaw** [comment]
fixed!
