### ISSUE TITLE
Better release listing

### ISSUE THREAD

**Issue by Sandertv** [poggit/poggit#73]
The title says pretty much everything.
I was thinking it could be a good idea to order the Review list on highest score from voting, for example a plugin with 5 upvotes would be at the start of the review list, while a plugin with 5 downvotes would be all the way at the end of the Review list.

I'm not sure if this is a great idea or not, I just thought it'd be a good idea for locating better/worse plugins.

**Comment by Awzaw** [comment]
Maybe - and I might add a stats page showing a summary of plugin scores, votes, downloads etc

**Comment by SOF3** [comment]
Yeah, pretty much everything... The current release list is almost only basic.

**Comment by SOF3** [comment]
We still need a "sort by votes" and "sort by downloads"

**Comment by SOF3** [comment]
It still doesn't look nice, but I can consider it resolved.
