### ISSUE TITLE
Extended badges

### ISSUE THREAD

**Issue by Thunder33345** [poggit/poggit#75]
Preferably another option to use the shields standard https://github.com/badges/shields to keep most badges the same

examples would be like
![](https://img.shields.io/badge/Poggit%20Status-Lint%20Pass-brightgreen.svg) ![](https://img.shields.io/badge/Poggit%20Status-3%20lints-brightgreen.svg)

**Comment by SOF3** [comment]
@Thunder33345 wanna do it yourself? :D

An advantage of the Poggit badge format right now is that it allows dynamic size, but this is a disadvantage at the same time.

**Comment by Thunder33345** [comment]
@SOF3 by doing it yourself i can only do something like so with a link to the poggit repo which works as of now
<img src="https://img.shields.io/badge/Poggit-view-brightgreen.svg"/> 
but lets just say it would be better if it was dynamic

**Comment by SOF3** [comment]
@thunder33345 I meant a pull request :P

**Comment by SOF3** [comment]
Implemented in endpoint /ci.shield

For example:
`https://poggit.pmmp.io/ci.shield/pmmp/PocketMine-DevTools/~` ![](https://poggit.pmmp.io/ci.shield/pmmp/PocketMine-DevTools/~)
`https://poggit.pmmp.io/ci.shied/poggit/libasynql/PoolExample` ![](https://poggit.pmmp.io/ci.shield/poggit/libasynql/PoolExample)
