### ISSUE TITLE
Lint formatting issue

### ISSUE THREAD

**Issue by jasonw4331** [poggit/poggit#76]
I'm pretty sure that the box is supposed to be around the text, but in this picture, the text goes out of the box
![screenshot 38](https://cloud.githubusercontent.com/assets/16521025/24572271/3c1a540c-1645-11e7-8279-d49946cfc140.png)

**Comment by Awzaw** [comment]
Thanks, l'll fix that today - there are other pages that need CSS tweaks for too especially regarding extra-long paths with wordbreak/overflow/scrolling so keep your eyes open. A bootstrap revamp is maybe in the works though :-)

**Comment by SOF3** [comment]
We should actually make these lint boxes spoilers instead.
