### ISSUE TITLE
You can rate your own plugins

### ISSUE THREAD

**Issue by TheDiamondYT1** [poggit/poggit#77]
https://poggit.pmmp.io/p/JellyLegs/1.0.1

See my comment on my plugin above, and i could rate it 5/5. This shouldnt be allowed imo.

**Comment by Awzaw** [comment]
Your own review score isn't taken into account - I'll either forbid leaving reviews on your own plugins, or disable the score drop down

**Comment by SOF3** [comment]
Reviewing your own plugin still looks unreasonable despite the score.

**Comment by Awzaw** [comment]
Removed
