### ISSUE TITLE
Request:

### ISSUE THREAD

**Issue by jasonw4331** [poggit/poggit#78]
I noticed that the released plugins turns into reviewed plugins at about the 3rd page. I was wondering why the reviewed plugins were in the released section if they haven't been officially released yet. Is this unintentional or on purpose?

**Comment by SOF3** [comment]
We haven't developed an active reviewing community to make some plugins reach the number of upvotes required for the "Voted" state yet, and we don't have enough manpower to approve plugins (enough for "Checked" but not enough for "Approved"), so we are showing "Checked" plugins for the while.
