### ISSUE TITLE
Page not switched when travelling in history

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#80]
This is reported in neighbordog/jquery-paginate#2

**Comment by Awzaw** [comment]
I just fixed an error whereby on reload the page-next button was  sometimes broken, did 87d1c8b5ec1d53ceff07bb4b131acdd1ae760a1a fix this one too?

**Comment by SOF3** [comment]
Still happening. On Chrome 58.0 on Windows 8.1

**Comment by SOF3** [comment]
Also note that this issue only happens **when switching pages between different pages**. This does not happen if the page is changed (not just the hash).

**Comment by Awzaw** [comment]
Now I see what you mean

**Comment by Awzaw** [comment]
Fixed by 99386e86dd2ecaff262f1a239c12cd2aa7e50683 :-)

**Comment by SOF3** [comment]
Nice 👍
