### ISSUE TITLE
Window icons missing

### ISSUE THREAD

**Issue by jarne** [poggit/poggit#85]
In all windows on Poggit, which are jQuery UI windows I think, the close-icons are missing. When you download jQuery UI, there is a folder named "images" where the icons are in. This folder must be placed in the same folder like jQuery UI's CSS file.

No important issue, but I've just noticed it because I've also forgot it this morning.

Now:

<img width="902" alt="ohne titel" src="https://cloud.githubusercontent.com/assets/15860314/25588984/f9ec113c-2eaa-11e7-983f-b62081926124.png">

Should be like:

<img width="567" alt="2" src="https://cloud.githubusercontent.com/assets/15860314/25589015/1c036658-2eab-11e7-9edb-63e073ff7f2c.png">

**Comment by Awzaw** [comment]
Thanks, we were using the CDN so it was probably related to the load order with bootstrap. Loading everything from the server instead now, should be fixed.
