### ISSUE TITLE
Multiple labels of the same plugin?

### ISSUE THREAD

**Issue by jasonw4331** [poggit/poggit#87]
notice on the right, there are repeat labels of the projects I have recently enabled
![screenshot 2017-05-05 at 9 50 26 am](https://cloud.githubusercontent.com/assets/16521025/25748464/224f2b16-3179-11e7-8621-2c608aa08733.png)

**Comment by SOF3** [comment]
Note: it's builds, not releases.

**Comment by jasonw4331** [comment]
they all say its build 1

**Comment by Awzaw** [comment]
Fixed
