### ISSUE TITLE
Can't login using my Github account

### ISSUE THREAD

**Issue by MisteFr** [poggit/poggit#91]
This the error, i tried four times but it doesn't work
![capture d ecran 2017-05-19 a 23 41 58](https://cloud.githubusercontent.com/assets/17687222/26267916/d78d3530-3cec-11e7-83dd-e3db6145a70f.png)
This was my fisrt time on poggit

**Comment by Awzaw** [comment]
Can you try again now?

**Comment by MisteFr** [comment]
Ok

**Comment by SOF3** [comment]
Fixed in 84d45794865389c72cb7e2d6f4119530a1f2aef9
