### ISSUE TITLE
GFM formatting

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#93]
GFM returns `<code>` for code spans. The CSS in Poggit displays them as blocks while they should be inline.

See https://poggit.pmmp.io/p/Hormones/ for example.

**Comment by Awzaw** [comment]
Changed in 86ed50f00467721ca2cca1bda2ee84fdc9fbc0d9. I wouldn't be surprised if removing this will require CSS tweaks for other plugins, however :-/

**Comment by SOF3** [comment]
Seems to be fixed.
