### ISSUE TITLE
Bug: Save as Draft submits the release

### ISSUE THREAD

**Issue by Sandertv** [poggit/poggit#95]
Hi,
When trying to release a plugin today I, I noticed something weird. I chose a release that had no icon because the slash was a backslash, so I fixed that on a later commit. I then saved it as draft, so I could use it for the fields I'd have to fill out again to release the new commit.

When I selected the new commit for release, I noticed that all the fields WERE still there, but when I tried to enter the version I had saved as draft it said I already submitted a plugin with that version, which I apparently had, by clicking the Save as Draft button.

**Steps to Reproduce:**
- Select a commit/build in CI to release.
- Fill out the fields. Instead of clicking release plugin, click save as draft.
- The website will redirect you to the Release page.
- Go back to CI, and look at the box below the plugin mentioning the last release.
- Try to release a new commit with the same version as before. Notice the error saying you released this version already.

**Comment by Awzaw** [comment]
I see what you mean, but since any change at all to the package (see section 3 are semver.org) 'should' involve a change to the version according to semver's guidelines, this might be a moot point depending on your interpretation of semver's guidelines. What do you think @SOF3 ?

**Comment by SOF3** [comment]
@Awzaw Since a draft is not released, the rule probably doesn't apply since you don't have to bump a version every release.
I recommend only allowing one draft release per project which isn't linked to a specific build, with the version name "draft".
