### ISSUE TITLE
Forks can not be buildt / stuck at "loading information" at https://poggit.pmmp.io/ci

### ISSUE THREAD

**Issue by inxomnyaa** [poggit/poggit#96]
When clicking the buildt toggle to turn on on a repo that is forked, the build will not start.
![image](https://cloud.githubusercontent.com/assets/8733998/26569917/e21abc60-450d-11e7-8cef-ebe613575ad3.png)
Affects: https://poggit.pmmp.io/ci
Repo where the issue appears: https://github.com/thebigsmileXD/BetterGen

**Comment by Awzaw** [comment]
It's nothing to do with repos being forked; that repo is is larger than the current Poggit 10MB repo limit.

**Comment by SOF3** [comment]
Poggit definitely does not take forks into consideration anywhere except for displaying the fork icon in the CI admin page.

**Comment by inxomnyaa** [comment]
> It's nothing to do with repos being forked; that repo is is larger than the current Poggit 10MB repo limit.
 
Then please add this as information on the loading details screen. ty.
